// @ts-nocheck
/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Check if the app has any games configured (determines which screen to show on startup).
 */
async checkConfigStatus() : Promise<Result<ConfigStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_config_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeSplashscreen() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_splashscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch all dashboard data in a single command for minimal IPC overhead.
 * 
 * The corridor is derived server-side; in Safe Mode the stats and charts
 * exclude mods with `is_safe = 0`.
 */
async getDashboardStats() : Promise<Result<DashboardPayload, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dashboard_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan all enabled mods for a game and return their keybindings.
 * 
 * This is a filesystem-heavy operation (reads INI files from disk),
 * so it's a separate command from the main dashboard payload.
 */
async getActiveKeybindings(gameId: string) : Promise<Result<ActiveKeyBinding[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_keybindings", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceViewModel(input: WorkspaceViewModelInput) : Promise<Result<WorkspaceViewModel, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_view_model", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeWorkspaceSwitch(input: WorkspaceSwitchInput) : Promise<Result<WorkspaceSwitchResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_workspace_switch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the last N lines of the application log.
 */
async getLogs(limit: number | null, count: number | null) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_logs", { limit, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the logs directory in the OS file explorer.
 */
async openLogFolder() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset the application setup by clearing all data from the database.
 * Before clearing, a backup copy of `app.db` is saved to the trash folder.
 * No mod files or folders on disk are deleted — only database records are cleared.
 */
async resetDatabase() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if a given absolute path exists on the disk.
 * Bypasses restrictive Tauri v2 plugin-fs scopes.
 */
async checkPathExistsCmd(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("check_path_exists_cmd", { path });
},
/**
 * Ensure a directory exists on disk.
 * Used by frontend import flows to avoid direct plugin-fs dependency in
 * tests/runtime. Creation is confined to configured mods roots — this used
 * to `create_dir_all` any absolute path the client sent.
 */
async ensureDirCmd(path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_dir_cmd", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Auto-detect games by scanning an XXMI root folder.
 * Validates each subfolder, saves valid games to ConfigService.
 */
async autoDetectGames(rootPath: string) : Promise<Result<GameConfig[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auto_detect_games", { rootPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually add a single game by path and type.
 * Validates the folder, checks for duplicates, saves to ConfigService.
 */
async addGameManual(gameType: string, path: string) : Promise<Result<GameConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_game_manual", { gameType, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save confirmed games from onboarding into the database/settings
 */
async saveOnboardingGames(games: GameConfig[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_onboarding_games", { games }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all configured games.
 */
async getGames() : Promise<Result<GameConfig[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_games") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch the 3DMigoto Loader (if not running) and then the Game.
 * Covers: US-10.1, TC-10.1-01
 */
async launchGame(gameId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_game", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the game schema (categories + filters) for a specific game type.
 * Falls back to default [Character, Weapon, UI, Other] if schema.json is missing/corrupt.
 * 
 * Covers: NC-3.4-02 (Schema Load Failure → fallback)
 */
async getGameSchema(gameType: number) : Promise<Result<GameSchema, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_schema", { gameType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single object by ID (full details including metadata).
 */
async getObject(id: string) : Promise<Result<GameObject | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_object", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the MasterDB JSON for a specific game type.
 * Loads from `resources/databases/{game_type}.json`.
 * Returns array JSON for frontend compatibility (even if file uses new object format).
 * When hash_db is present in source, merges hashes into matching entries.
 */
async getMasterDb(gameType: number) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_master_db", { gameType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search Master DB from Rust to offload fuzzy matching from the JS thread.
 * Finds the top results matching `query`, optionally filtering by `object_type`.
 */
async searchMasterDb(gameType: number, query: string, objectType: string | null) : Promise<Result<SearchResultEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_master_db", { gameType, query, objectType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Match a single object name against the MasterDB for a specific game.
 * Uses staged quick matcher semantics and adapter labels.
 * 
 * This is used for the "Sync with DB" context menu action on individual objects/folders.
 */
async matchObjectWithDb(gameType: number, objectName: string) : Promise<Result<MatchedDbEntry | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("match_object_with_db", { gameType, objectName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pin or unpin an object in the database.
 */
async pinObject(id: string, pin: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pin_object", { id, pin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelScanCmd() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_scan_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect archive files (ZIP, 7z, RAR) in the mods directory.
 * 
 * # Covers: US-2.1
 */
async detectArchivesCmd(modsPath: string) : Promise<Result<ArchiveInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_archives_cmd", { modsPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Extract a single archive with optional password, smart flattening, and backup.
 * Automatically suppresses the file watcher during operation.
 * 
 * # Covers: TC-2.1-01, TC-2.1-04, TC-2.1-05, EC-2.06
 */
async extractArchiveCmd(archivePath: string, modsDir: string, password: string | null, overwrite: boolean | null, customName: string | null, disableAfter: boolean | null, unpackNested: boolean | null, onProgress: TAURI_CHANNEL<ExtractionEvent>) : Promise<Result<ExtractionResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_archive_cmd", { archivePath, modsDir, password, overwrite, customName, disableAfter, unpackNested, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Analyze an archive without extracting (file count, has_ini, size, etc).
 * 
 * # Covers: US-2.1 Pre-Extraction Analysis
 */
async analyzeArchiveCmd(archivePath: string) : Promise<Result<ArchiveAnalysis, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_archive_cmd", { archivePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Light match check against a specific target object name.
 * Used for auto-organize validation after archive extraction.
 * 
 * # Covers: Req-38 (Auto-organizer Match Detection)
 */
async matchCheckFolderCmd(folderPath: string, targetObjectName: string, gameType: number) : Promise<Result<MatchCheckResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("match_check_folder_cmd", { folderPath, targetObjectName, gameType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abort an ongoing extraction operation.
 */
async abortExtractionCmd() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_extraction_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect shader/buffer hash conflicts across INI files.
 * 
 * # Covers: US-2.Z, TC-2.4-01
 */
async detectConflictsCmd(iniPaths: string[]) : Promise<Result<ConflictInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_conflicts_cmd", { iniPaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect conflicts by scanning the entire mods folder for INI files.
 * 
 * More efficient for frontend usage as it avoids passing thousands of paths.
 * # Covers: US-2.Z
 */
async detectConflictsInFolderCmd(modsPath: string) : Promise<Result<ConflictInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_conflicts_in_folder_cmd", { modsPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually set watcher suppression state (e.g. for bulk operations).
 * 
 * # Covers: EC-2.06
 */
async setWatcherSuppression(suppressed: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_watcher_suppression", { suppressed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lazily resolve thumbnail for a single mod folder.
 * Called per-card from the frontend after the folder list is rendered.
 * Delegates to ThumbnailCache::resolve() which caps concurrency (4 max),
 * checks folder-keyed L1, and falls back to FS traversal + image processing.
 */
async getModThumbnail(gameId: string, folderPath: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mod_thumbnail", { gameId, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openInExplorer(gameId: string, path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_explorer", { gameId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revealObjectInExplorer(gameId: string, objectId: string, objectName: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_object_in_explorer", { gameId, objectId, objectName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a naming conflict where both "X" and "DISABLED X" exist on disk.
 */
async resolveConflict(gameId: string, keepPath: string, duplicatePath: string, strategy: ConflictStrategy) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_conflict", { gameId, keepPath, duplicatePath, strategy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get detailed file listings for both enabled and disabled versions of a conflicting folder.
 * Used by the enhanced ConflictResolveDialog for side-by-side comparison.
 */
async getConflictDetails(gameId: string, enabledPath: string, disabledPath: string) : Promise<Result<ConflictDetails, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflict_details", { gameId, enabledPath, disabledPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ignoreObjectConflict(gameId: string, objectId: string, modIds: string[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ignore_object_conflict", { gameId, objectId, modIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revokeObjectConflict(gameId: string, objectId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revoke_object_conflict", { gameId, objectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIgnoredObjectConflicts(gameId: string) : Promise<Result<IgnoredConflict[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_ignored_object_conflicts", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameModFolder(folderPath: string, newName: string, gameId: string) : Promise<Result<RenameResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_mod_folder", { folderPath, newName, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importModsFromPaths(paths: string[], targetDir: string) : Promise<Result<BulkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_mods_from_paths", { paths, targetDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ingestDroppedFolders(paths: string[], modsPath: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ingest_dropped_folders", { paths, modsPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bulkToggleMods(gameId: string, paths: string[], enable: boolean) : Promise<Result<BulkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bulk_toggle_mods", { gameId, paths, enable }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bulkDeleteMods(gameId: string, paths: string[]) : Promise<Result<BulkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bulk_delete_mods", { gameId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bulkUpdateInfo(gameId: string, paths: string[], update: ModInfoUpdate) : Promise<Result<BulkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bulk_update_info", { gameId, paths, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bulkToggleFavorite(gameId: string, folderPaths: string[], favorite: boolean) : Promise<Result<BulkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bulk_toggle_favorite", { gameId, folderPaths, favorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bulkPinMods(gameId: string, folderPaths: string[], pin: boolean) : Promise<Result<BulkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bulk_pin_mods", { gameId, folderPaths, pin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleModSafe(gameId: string, folderPath: string, safe: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_mod_safe", { gameId, folderPath, safe }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suggestRandomMods(gameId: string) : Promise<Result<RandomModProposal[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_random_mods", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveModConflicts(gameId: string) : Promise<Result<ConflictInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_mod_conflicts", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readModInfo(gameId: string, folderPath: string) : Promise<Result<ModInfo | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_mod_info", { gameId, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateModInfo(gameId: string, folderPath: string, update: ModInfoUpdate) : Promise<Result<ModInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_mod_info", { gameId, folderPath, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModCategory(gameId: string, folderPath: string, category: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mod_category", { gameId, folderPath, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setObjectModsCategory(gameId: string, objectId: string, category: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_object_mods_category", { gameId, objectId, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMoveTargetsForObject(gameId: string, objectId: string) : Promise<Result<WorkspaceMoveTarget[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_move_targets_for_object", { gameId, objectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveModsToObject(input: MoveModsToObjectInput) : Promise<Result<BulkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_mods_to_object", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateModThumbnail(gameId: string, folderPath: string, sourcePath: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_mod_thumbnail", { gameId, folderPath, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pasteThumbnail(gameId: string, folderPath: string, imageData: number[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paste_thumbnail", { gameId, folderPath, imageData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the thumbnail file for a mod folder (if found) and invalidate cache.
 */
async deleteModThumbnail(folderPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mod_thumbnail", { folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMod(path: string, gameId: string) : Promise<Result<DeleteModResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mod", { path, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreMod(trashId: string, gameId: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_mod", { trashId, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTrash() : Promise<Result<TrashMetadata[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async emptyTrash() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("empty_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModIniFiles(gameId: string, folderPath: string) : Promise<Result<IniFileEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mod_ini_files", { gameId, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readModIni(gameId: string, folderPath: string, fileName: string) : Promise<Result<IniDocument, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_mod_ini", { gameId, folderPath, fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeModIni(gameId: string, folderPath: string, fileName: string, lineUpdates: IniLineUpdate[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_mod_ini", { gameId, folderPath, fileName, lineUpdates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModPreviewImages(gameId: string, folderPath: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mod_preview_images", { gameId, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveModPreviewImage(gameId: string, folderPath: string, objectName: string, imageData: number[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_mod_preview_image", { gameId, folderPath, objectName, imageData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeModPreviewImage(gameId: string, folderPath: string, imagePath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_mod_preview_image", { gameId, folderPath, imagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearModPreviewImages(gameId: string, folderPath: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_mod_preview_images", { gameId, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: AppSettings) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveGame(gameId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_game", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutoCloseLauncher(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_auto_close_launcher", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runMaintenance() : Promise<Result<[number, number], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_maintenance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetPinWithRecoveryCode(code: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_pin_with_recovery_code", { code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearOldThumbnails() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_old_thumbnails") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCustomThemes() : Promise<Result<ThemeMetadata[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_custom_themes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadCustomTheme(id: string) : Promise<Result<CustomTheme, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_custom_theme", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveCustomTheme(theme: CustomTheme) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_custom_theme", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCustomTheme(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_custom_theme", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getObjectsCmd(filter: ObjectFilter) : Promise<Result<GetObjectsResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_objects_cmd", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCategoryCountsCmd(gameId: string) : Promise<Result<CategoryCount[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_category_counts_cmd", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createObjectCmd(input: CreateObjectInput) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_object_cmd", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateObjectCmd(id: string, updates: UpdateObjectInput) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_object_cmd", { id, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyObjectMatchCmd(input: ApplyObjectMatchInput) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_object_match_cmd", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteObjectCmd(id: string, force: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_object_cmd", { id, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCorridorState(gameId: string) : Promise<Result<CorridorSnapshot, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_corridor_state", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getApplyProgress(gameId: string) : Promise<Result<ApplyProgressSnapshot | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_apply_progress", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCollections(gameId: string) : Promise<Result<CollectionSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_collections", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCollection(gameId: string, name: string, saveMode: CreateCollectionMode | null, sourceCollectionId: string | null) : Promise<Result<CollectionSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_collection", { gameId, name, saveMode, sourceCollectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyCollection(gameId: string, collectionId: string, ignoreMissing: boolean | null) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_collection", { gameId, collectionId, ignoreMissing }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCollection(gameId: string, id: string, name: string | null) : Promise<Result<CollectionSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_collection", { gameId, id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replaceCollectionWithCurrentState(gameId: string, collectionId: string) : Promise<Result<CollectionSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_collection_with_current_state", { gameId, collectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCollection(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_collection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appStartupCheck() : Promise<Result<PipelineTask[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_startup_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveRecoveryTask(taskId: string, action: RecoveryAction) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_recovery_task", { taskId, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCollectionPreview(collectionId: string, gameId: string) : Promise<Result<CollectionPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_collection_preview", { collectionId, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewApplyCollection(gameId: string, collectionId: string) : Promise<Result<ApplyPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_apply_collection", { gameId, collectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPin(pin: string, recoveryCode: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_pin", { pin, recoveryCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyPin(pin: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_pin", { pin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPinStatus() : Promise<Result<PinStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pin_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deepmatchScannerCmd(gameId: string, gameName: string, gameType: string, masterDbType: number, modsPath: string, preserveExistingMappings: boolean, onProgress: TAURI_CHANNEL<ScanEvent>) : Promise<Result<SyncResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deepmatch_scanner_cmd", { gameId, gameName, gameType, masterDbType, modsPath, preserveExistingMappings, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deep Match Scanner preview.
 * This path runs explicit matching preview without writing to DB.
 * Frontend shows a review modal for the user to confirm/override matches.
 * 
 * # Covers: US-2.3 (Review & Organize UI)
 */
async deepmatchPreviewCmd(gameId: string, modsPath: string, gameType: number, onProgress: TAURI_CHANNEL<ScanEvent>, specificPaths: string[] | null) : Promise<Result<ScanPreviewItem[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deepmatch_preview_cmd", { gameId, modsPath, gameType, onProgress, specificPaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deep Match Scanner preview for object IDs already selected in the workspace UI.
 * Backend resolves DB paths and filters stale or escaped paths before scanning.
 */
async deepmatchPreviewForObjectsCmd(input: DeepmatchPreviewForObjectsInput, onProgress: TAURI_CHANNEL<ScanEvent>) : Promise<Result<ScanPreviewItem[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deepmatch_preview_for_objects_cmd", { input, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Phase 2: Commit user-confirmed scan results to DB.
 * Called after the user reviews and confirms/overrides matches in the review modal.
 * 
 * # Covers: US-2.3 (Review & Organize UI — Confirm)
 */
async commitScanCmd(gameId: string, gameName: string, gameType: string, modsPath: string, items: ConfirmedScanItem[]) : Promise<Result<SyncResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_scan_cmd", { gameId, gameName, gameType, modsPath, items }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compute percentage scores for a specific batch of candidates against a folder.
 * Used by the Scan Review Modal to lazy-load accurate matching percentages.
 * 
 * # Covers: US-2.3 (Review & Organize UI — Lazy Scoring)
 */
async scoreCandidatesBatchCmd(folderPath: string, candidateNames: string[], gameType: number) : Promise<Result<Partial<{ [key in string]: number }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("score_candidates_batch_cmd", { folderPath, candidateNames, gameType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFolderEntriesCmd(folderPath: string, gameId: string) : Promise<Result<FolderEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_folder_entries_cmd", { folderPath, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconcileDiskStateCmd(gameId: string, reason: DiskReconcileReason, changedPaths: string[] | null, forceFull: boolean | null) : Promise<Result<DiskReconcileResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_disk_state_cmd", { gameId, reason, changedPaths, forceFull }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the file watcher for a specific path.
 * Emits `mod_watch:event` to the frontend.
 * 
 * Delegates the full lifecycle (thread spawning, event loop, DB sync) to
 * `services::scanner::watcher::lifecycle::start_watcher`.
 */
async startWatcher(path: string, gameId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_watcher", { path, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the file watcher. Cleanly drops the `RecommendedWatcher`,
 * terminating the background event loop thread.
 * 
 * Called by the frontend in `useEffect` cleanup when the active game changes
 * or the component unmounts.
 * 
 * # Covers: req-05 AC-05.2.2, req-28 (Game Switch → stop → init)
 */
async stopWatcher() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dupScanStart(gameId: string, modsRoot: string, onEvent: TAURI_CHANNEL<DupScanEvent>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dup_scan_start", { gameId, modsRoot, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dupScanCancel() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dup_scan_cancel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dupScanGetReport(pin: string | null) : Promise<Result<DupScanReport | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dup_scan_get_report", { pin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dupResolveBatch(requests: ResolutionRequest[], gameId: string) : Promise<Result<ResolutionSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dup_resolve_batch", { requests, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIgnoredPairs(gameId: string) : Promise<Result<WhitelistEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ignored_pairs", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeIgnoredPair(entryId: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_ignored_pair", { entryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for metadata updates from the remote manifest.
 * 
 * Returns whether an update was applied and the current version.
 */
async checkMetadataUpdate() : Promise<Result<MetadataSyncResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_metadata_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch a missing asset file from the remote CDN.
 * 
 * Returns the local path to the cached asset, or null if the fetch failed.
 */
async fetchMissingAsset(assetName: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_missing_asset", { assetName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update hotkey config and re-register OS hotkeys.
 * This saves settings to DB AND tells the HotkeyManager to re-register.
 */
async updateHotkeyConfig() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_hotkey_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a new in-app browser tab (creates a new Webview).
 * Returns the webview label so the frontend can track the tab.
 */
async browserOpenTab(url: string, sessionId: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_open_tab", { url, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Navigate an existing browser tab to a new URL.
 */
async browserNavigate(label: string, url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_navigate", { label, url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Navigate an existing browser tab back in history.
 */
async browserGoBack(label: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_go_back", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Navigate an existing browser tab forward in history.
 */
async browserGoForward(label: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_go_forward", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reload an existing browser tab.
 */
async browserReloadTab(label: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_reload_tab", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear cookies and cache for a specific browser tab.
 */
async browserClearData(label: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_clear_data", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the configured browser homepage URL.
 */
async browserGetHomepage() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_get_homepage") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set a new browser homepage URL. Validates http/https scheme.
 */
async browserSetHomepage(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_set_homepage", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return all browser downloads ordered by most recent first.
 */
async browserListDownloads() : Promise<Result<BrowserDownloadDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_list_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel (and optionally delete the file for) a specific download.
 * 
 * An in-flight transfer is aborted by its background task, which also
 * deletes the partial file and marks the record `canceled`. Otherwise
 * (stale/finished record) only the DB status is updated here.
 */
async browserCancelDownload(id: string, deleteFile: boolean | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_cancel_download", { id, deleteFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a download record (and optionally the file on disk).
 */
async browserDeleteDownload(id: string, deleteFile: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_delete_download", { id, deleteFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove all downloads with status `imported`.
 */
async browserClearImported() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_clear_imported") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove old downloads that exceed the configured retention period.
 */
async browserClearOldDownloads() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_clear_old_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Queue multiple import jobs for a set of finished download IDs with a chosen game.
 * Called by the Download Manager "Import Selected" bulk action after Game Picker confirms.
 */
async browserImportSelected(ids: string[], gameId: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_import_selected", { ids, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return all pending/active import jobs.
 */
async browserListImportQueue() : Promise<Result<ImportJobDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_list_import_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Confirm a `needs_review` import job — provide game, category, and optional object.
 */
async browserConfirmImport(jobId: string, gameId: string, category: string, objectId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_confirm_import", { jobId, gameId, category, objectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Skip / cancel a specific import job and remove its staging folder.
 */
async browserCancelImport(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_cancel_import", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A keybinding entry extracted from an enabled mod's INI file.
 */
export type ActiveKeyBinding = { mod_name: string; section_name: string; key: string | null; back: string | null }
export type AiConfig = { enabled: boolean; api_key: string | null; base_url: string | null }
/**
 * Unified error type for Tauri command boundaries.
 * Each domain error converts into this for consistent frontend handling.
 */
export type AppError = { type: "Corridor"; payload: CorridorError } | { type: "Collection"; payload: CollectionError } | { type: "Pin"; payload: PinError } | { type: "Metadata"; payload: MetadataError } | { type: "Browser"; payload: BrowserError } | { type: "Scanner"; payload: ScannerError } | { type: "Security"; payload: string } | { type: "NotFound"; payload: string } | { type: "Internal"; payload: string } | { type: "Db"; payload: string } | { type: "Validation"; payload: string } | { type: "Io"; payload: string } | { type: "RuntimePathNotFound"; payload: { target: string } } | { type: "DuplicateConflict"; payload: DuplicateModInfo[] } | { type: "FileInUse"; payload: { path: string; processes: string[] } } | { type: "PathBusy"; payload: { path: string } } | { type: "ObjectHasMods"; payload: number } | 
/**
 * The user cancelled a long-running operation.
 * 
 * A variant rather than the `"ABORTED"` string the extractors used to
 * return: callers matched on that message text, so any rewording of an
 * error message could silently turn a cancel into a failure.
 */
{ type: "Cancelled" }
export type AppSettings = { theme: string; language: string; games: GameConfig[]; active_game_id: string | null; safe_mode: SafeModeConfig; ai: AiConfig; auto_close_launcher: boolean; hotkeys?: HotkeyConfig; keyviewer?: KeyViewerConfig }
export type ApplyObjectMatchInput = { game_id: string; object_id: string | null; folder_path: string | null; matched_entry_key: string | null; matched_alias_name: string | null; matched_confidence: number | null; matched_reason: string | null; matched_source: string | null }
/**
 * Preview data for applying a collection (before → after).
 */
export type ApplyPreview = { collection_name: string; current_snapshot: string | null; current_mods: CollectionMod[]; current_objects: CollectionObject[]; current_tree_nodes: PreviewTreeNode[]; target_mods: CollectionMod[]; target_objects: CollectionObject[]; target_tree_nodes: PreviewTreeNode[]; current_state_name: string | null; current_state_is_unsaved: boolean; current_projected_state: ProjectedCollectionState; target_projected_state: ProjectedCollectionState }
export type ApplyProgressSnapshot = { game_id: string; is_safe: boolean; phase: string; completed: number; total: number; current_item: string | null; warnings: string[]; final_state_name: string | null; final_mode: string | null; success: boolean }
/**
 * Result of applying a collection.
 */
export type ApplyResult = { success: boolean; mods_enabled: number; mods_disabled: number; objects_toggled: number; new_signature: string; warnings: string[]; final_state_name: string | null; final_mode: string | null; partial_apply: boolean; skipped_missing_paths: string[]; final_state_is_dirty: boolean; runtime_path_rewrites: WorkspacePathRewrite[] }
/**
 * Result of analyzing an archive before extraction.
 */
export type ArchiveAnalysis = { format: ArchiveFormat; file_count: number; has_ini: boolean; uncompressed_size: number; 
/**
 * The physical size of the archive file on disk.
 */
file_size_bytes: number; single_root_folder: string | null; 
/**
 * Whether the archive requires a password for extraction.
 */
is_encrypted: boolean; 
/**
 * Whether the archive contains other archives (e.g. .zip, .rar, .7z) inside it.
 */
contains_nested_archives: boolean; 
/**
 * Top entries for file tree preview (capped at 500).
 */
entries: ArchiveEntryInfo[] }
/**
 * A single entry in an archive (for file tree preview).
 */
export type ArchiveEntryInfo = { path: string; is_dir: boolean; size: number }
/**
 * Supported archive format.
 */
export type ArchiveFormat = "Zip" | "SevenZ" | "Rar"
/**
 * Info about a detected archive file.
 */
export type ArchiveInfo = { path: string; name: string; extension: string; size_bytes: number; has_ini: boolean; file_count: number; 
/**
 * Whether the archive requires a password for extraction.
 */
is_encrypted: boolean; 
/**
 * Whether the archive contains other archives (e.g. .zip, .rar, .7z).
 */
contains_nested_archives: boolean }
/**
 * DTO for the frontend download list.
 */
export type BrowserDownloadDto = { id: string; session_id: string | null; filename: string; file_path: string | null; source_url: string | null; status: string; bytes_total: number | null; bytes_received: number; error_msg: string | null; started_at: string; finished_at: string | null }
/**
 * Errors from the in-app browser: webview lifecycle, downloads, and the
 * import pipeline that turns a download into a placed mod.
 */
export type BrowserError = "WindowUnavailable" | { WebviewNotFound: { label: string } } | { InvalidUrl: string } | { Download: string } | { JobIncomplete: { job_id: string; field: string } } | { Import: string } | "QueueClosed" | { Io: string } | { Db: string }
export type BulkActionError = { path: string; error: AppError }
export type BulkResult = { success: string[]; failures: BulkActionError[]; collection_impact: CollectionReferenceImpact; path_rewrites: WorkspacePathRewrite[] }
export type CategoryCount = { object_type: string; count: number }
export type CategoryDef = { name: string; 
/**
 * Display label for the category. Falls back to `name` if absent.
 */
label?: string | null; icon: string; color: string; 
/**
 * Per-category metadata filter fields. If absent, no metadata editing for this category.
 */
filters?: FilterDef[] | null }
/**
 * A single slice of the category distribution pie chart.
 */
export type CategorySlice = { category: string; count: number }
/**
 * Errors specific to collection operations.
 */
export type CollectionError = { NotFound: { id: string } } | { DuplicateName: { name: string } } | { MissingMods: { count: number; paths: string[] } } | { Validation: string } | { Db: string } | { Corridor: CorridorError } | { Io: string } | { FileInUse: { path: string; processes: string[] } } | { PathBusy: { path: string } }
/**
 * A unified member type for collections.
 */
export type CollectionMember = ({ kind: "mod" } & CollectionMod) | ({ kind: "object" } & CollectionObject) | ({ kind: "root" } & CollectionRoot)
/**
 * A single mod member of a collection (from `collection_mods`).
 */
export type CollectionMod = { kind: MemberKind; collection_id: string; mod_id: string | null; mod_path: string; mod_path_key: string | null; object_id: string; display_name: string | null; preview_path: string | null; node_type: string | null; warnings: string[]; is_enabled: boolean }
/**
 * A single object member of a collection (from `collection_objects`).
 */
export type CollectionObject = { kind: MemberKind; collection_id: string; object_id: string; is_enabled: boolean; display_name: string | null; path_key: string | null }
export type CollectionPathRewrite = { from: string; to: string }
/**
 * Preview data for a collection.
 */
export type CollectionPreview = { collection: CollectionSummary; members: CollectionMember[]; mods: CollectionMod[]; objects: CollectionObject[]; roots: CollectionRoot[]; tree_nodes: PreviewTreeNode[]; projected_state: ProjectedCollectionState }
export type CollectionReferenceImpact = { affected_collection_count: number; affected_collection_names: string[]; rewritten_paths: CollectionPathRewrite[]; missing_paths: string[] }
/**
 * A root entry (from `collection_roots`).
 */
export type CollectionRoot = { kind: MemberKind; collection_id: string; root_path: string; root_path_key: string; display_name: string; display_name_key: string; object_id: string | null; object_name: string | null; object_type: string | null; root_kind: string; is_safe: boolean; is_enabled: boolean; thumbnail_hint: string | null; corridor_source: string | null }
/**
 * Summary returned in list views.
 */
export type CollectionSummary = { id: string; name: string; is_safe: boolean; is_unsaved: boolean; is_active: boolean; signature: string | null; updated_at: string; raw_member_count: number; mod_count: number }
/**
 * Represents a folder naming collision discovered during sync or organize.
 */
export type CollisionInfo = { 
/**
 * Unique ID for the collision (usually hash of target path)
 */
id: string; 
/**
 * The mod folder we are trying to move/place
 */
sourcePath: string; 
/**
 * The destination path that already exists
 */
targetPath: string; 
/**
 * Name of the object this mod belongs to
 */
objectName: string; 
/**
 * ID of the mod already occupying the target path (if indexed)
 */
existingModId: string | null }
/**
 * Startup config status returned to frontend
 */
export type ConfigStatus = "FreshInstall" | "HasConfig"
/**
 * User-confirmed item sent back from the review modal.
 */
export type ConfirmedScanItem = { folderPath: string; displayName: string; isDisabled: boolean; matchedEntryKey: string | null; matchedAliasName: string | null; matchedConfidence: number | null; matchedReason: string | null; objectType: string | null; thumbnailPath: string | null; tagsJson: string | null; metadataJson: string | null; hashDbJson: string | null; customSkinsJson: string | null; dbThumbnail: string | null; skip: boolean; moveFromTemp?: boolean }
export type ConflictDetails = { enabled: FolderDetail; disabled: FolderDetail }
/**
 * A group of folders sharing the same base name in the same parent directory.
 * Created when both "X" and "DISABLED X" exist on disk.
 */
export type ConflictGroup = { 
/**
 * Stable identifier: hash(parent_dir + base_name)
 */
group_id: string; 
/**
 * The normalized base name (without disabled prefix)
 */
base_name: string; 
/**
 * All member folders in this conflict
 */
members: ConflictMember[] }
/**
 * Information about a shader/buffer hash conflict.
 */
export type ConflictInfo = { 
/**
 * The conflicting hash value.
 */
hash: string; 
/**
 * Section name where the hash was found.
 */
section_name: string; 
/**
 * Paths of the mods that conflict.
 */
mod_paths: string[]; 
/**
 * Whether at least two conflicting mods are currently enabled.
 */
is_active: boolean }
/**
 * A single member of a conflict group (for the Resolve dialog).
 */
export type ConflictMember = { 
/**
 * Full absolute path
 */
path: string; 
/**
 * Actual folder name on disk
 */
folder_name: string; 
/**
 * Whether the folder is enabled
 */
is_enabled: boolean; 
/**
 * Last modified time (epoch seconds)
 */
modified_at: number; 
/**
 * Total size in bytes
 */
size_bytes: number }
/**
 * How to break a duplicate pair apart.
 * 
 * An enum rather than the `&str` the command used to match on: an unknown
 * spelling used to surface as a runtime "Unknown strategy" error.
 */
export type ConflictStrategy = 
/**
 * Keep the enabled folder; uniquify the disabled duplicate.
 */
"keep_enabled" | 
/**
 * Keep the disabled folder; uniquify the enabled duplicate.
 */
"keep_disabled" | 
/**
 * Keep both, renaming the duplicate's base name to "<base> (copy)".
 */
"separate"
/**
 * Errors specific to corridor operations.
 */
export type CorridorError = { NoModsPath: { game_id: string } } | { GameNotFound: { game_id: string } } | { Db: string } | { Collection: CollectionError }
/**
 * Lightweight snapshot returned to the frontend.
 */
export type CorridorSnapshot = { game_id: string; is_safe: boolean; active_collection_id: string | null; active_collection_name: string | null; current_signature: string; is_dirty: boolean; current_mods: CollectionMod[]; current_objects: CollectionObject[]; current_tree_nodes: PreviewTreeNode[]; projected_state: ProjectedCollectionState }
/**
 * Input for creating a new collection.
 */
export type CreateCollectionMode = "save_current_state" | "clone_snapshot"
export type CreateObjectInput = { game_id: string; name: string; folder_path: string | null; object_type: string; sub_category: string | null; status: number | null; metadata: JsonValue | null; thumbnail_url: string | null; hash_db: HashDbPayload | null; custom_skins: CustomSkinsPayload | null }
/**
 * A named skin/outfit with aliases.
 */
export type CustomSkin = { name: string; aliases?: string[]; thumbnail_skin_path?: string | null; rarity?: string | null }
/**
 * Strongly-typed payload for custom skins attached to the master DB
 */
export type CustomSkinsPayload = Partial<{ [key in string]: string }>
export type CustomTheme = { id: string; label: string; config: ThemeConfig }
/**
 * Full dashboard payload struct (mirrors the command type).
 */
export type DashboardPayload = { stats: DashboardStats; duplicate_waste_bytes: number; category_distribution: CategorySlice[]; game_distribution: GameSlice[]; recent_mods: RecentMod[] }
/**
 * Global overview statistics for the dashboard tiles.
 */
export type DashboardStats = { total_mods: number; enabled_mods: number; disabled_mods: number; total_size_bytes: number; total_games: number; total_collections: number }
/**
 * A single DB entry from Master DB.
 */
export type DbEntry = { name: string; tags?: string[]; object_type?: string; custom_skins?: CustomSkin[]; thumbnail_path?: string | null; metadata?: JsonValue | null; 
/**
 * Optional hashes for this entry (default: empty dictionary).
 * Maps a skin/variant name to its list of hashes. Invalid hashes are ignored.
 */
hash_db?: Partial<{ [key in string]: string[] }> }
export type DeepmatchPreviewForObjectsInput = { gameId: string; modsPath: string; gameType: number; objectIds: string[] }
export type DeleteModResult = { collection_impact: CollectionReferenceImpact }
export type DiskReconcileChangeCounts = { added: number; removed: number; renamed: number; modified: number }
export type DiskReconcileChangeSummary = { object_changes: DiskReconcileChangeCounts; mod_changes: DiskReconcileChangeCounts; object_sample_names: string[]; mod_sample_names: string[]; has_user_visible_changes: boolean }
export type DiskReconcilePathKind = "Object" | "Mod"
export type DiskReconcilePathUpdate = { from: string; to: string; kind: DiskReconcilePathKind }
export type DiskReconcileReason = "StartupBoot" | "OnboardingCompleted" | "ModsViewEntered" | "WindowRefocused" | "WatcherBatch" | "ManualRepair" | "GameSwitched" | "InternalMutation"
export type DiskReconcileResult = { game_id: string; reason: DiskReconcileReason; status: DiskReconcileStatus; error_message: string | null; changed_roots: string[]; objects_changed: boolean; folders_changed: boolean; collections_changed: boolean; runtime_file_changed: boolean; overlay_refresh_triggered: boolean; thumbnail_roots: string[]; cleared_selection_paths: string[]; path_updates: DiskReconcilePathUpdate[]; collection_reference_impact: CollectionReferenceImpact; change_summary: DiskReconcileChangeSummary }
export type DiskReconcileStatus = "Applied" | "SourceUnavailable"
/**
 * Streaming event contract for Epic 9 duplicate scan progress.
 */
export type DupScanEvent = 
/**
 * Emitted once when a scan session starts.
 */
{ event: "started"; data: { scanId: string; gameId: string; totalFolders: number } } | 
/**
 * Emitted after each processed folder.
 */
{ event: "progress"; data: { scanId: string; processedFolders: number; totalFolders: number; currentFolder: string; percent: number } } | 
/**
 * Emitted when a duplicate group candidate is produced.
 */
{ event: "match"; data: { scanId: string; group: DupScanGroup } } | 
/**
 * Emitted when a scan session finishes normally.
 */
{ event: "finished"; data: { scanId: string; totalGroups: number; totalMembers: number } } | 
/**
 * Emitted when a scan session is cancelled.
 */
{ event: "cancelled"; data: { scanId: string; processedFolders: number; totalFolders: number } }
/**
 * A cluster of potential duplicates with 2..N members.
 */
export type DupScanGroup = { groupId: string; confidenceScore: number; matchReason: string; isUnsafe: boolean; signals: DupScanSignal[]; members: DupScanMember[] }
/**
 * One mod folder inside a duplicate group.
 */
export type DupScanMember = { modId: string | null; version: number; folderPath: string; displayName: string; totalSizeBytes: number; fileCount: number; isSafe: boolean; confidenceScore: number; signals: DupScanSignal[] }
/**
 * Scan report root.
 * 
 * Group-based by design: one report contains many groups,
 * and each group contains many members.
 */
export type DupScanReport = { scanId: string; gameId: string; rootPath: string; totalGroups: number; totalMembers: number; groups: DupScanGroup[] }
/**
 * Normalized evidence signal used in both group and member scopes.
 */
export type DupScanSignal = { key: string; detail: string; score: number }
/**
 * Info about an enabled duplicate/conflicting mod for a given object.
 */
export type DuplicateModInfo = { mod_id: string; object_id: string; folder_path: string; actual_name: string; is_variant: boolean; parent_path: string }
/**
 * Progress events streamed to frontend during archive extraction via `Channel<ExtractionEvent>`.
 */
export type ExtractionEvent = 
/**
 * One file has been extracted (or skipped as directory).
 */
{ event: "fileProgress"; data: { fileName: string; fileIndex: number; totalFiles: number } }
/**
 * Result of an extraction operation.
 */
export type ExtractionResult = { archiveName: string; 
/**
 * Paths to all extracted mod root folders
 */
destPaths: string[]; filesExtracted: number; 
/**
 * Number of independent mod roots found and moved.
 */
modCount: number; success: boolean; error: string | null; aborted: boolean; collisions: CollisionInfo[] }
export type FileEntry = { name: string; size: number; is_ini: boolean }
export type FilterDef = { key: string; label: string; options: string[] }
export type FolderDetail = { path: string; folder_name: string; is_enabled: boolean; total_size: number; file_count: number; files: FileEntry[]; thumbnail_path: string | null }
/**
 * A single item in a folder listing (used by the Scan Review hover tooltip).
 */
export type FolderEntry = { name: string; is_dir: boolean }
export type GameConfig = { id: string; name: string; game_type: number; mod_path: string; game_exe: string; loader_exe: string | null; launch_args: string | null; 
/**
 * Transient warnings from path validation. NOT persisted to DB.
 */
warnings?: string[] }
/**
 * Represents a row in the `objects` table.
 */
export type GameObject = { id: string; game_id: string; name: string; folder_path: string; folder_path_key: string; status: number; object_type: string; sub_category: string | null; tags: string; metadata: string; hash_db: HashDbPayload | null; custom_skins: CustomSkinsPayload | null; thumbnail_path: string | null; is_pinned: boolean; is_auto_sync: boolean; created_at: string }
/**
 * Game schema defines available categories and filter fields per game type.
 * Loaded from bundled JSON resources, with fallback to defaults.
 */
export type GameSchema = { categories: CategoryDef[]; filters: FilterDef[]; 
/**
 * Optional stopwords to exclude during tokenization.
 */
stopwords?: string[]; 
/**
 * Optional short token whitelist (tokens normally filtered but allowed).
 */
short_token_whitelist?: string[]; 
/**
 * Optional INI key blacklist (keys to skip during extraction).
 */
ini_key_blacklist?: string[]; 
/**
 * Optional INI key whitelist (keys to include during extraction).
 */
ini_key_whitelist?: string[] }
/**
 * A single bar of the game distribution bar chart.
 */
export type GameSlice = { game_id: string; game_name: string; count: number }
export type GetObjectsResult = { objects: ObjectSummary[]; lost_objects: string[] }
/**
 * Strongly-typed payload for an object's known hashed files
 */
export type HashDbPayload = Partial<{ [key in string]: string[] }>
/**
 * Hotkey configuration — persisted in AppSettings.
 */
export type HotkeyConfig = { 
/**
 * Whether hotkeys are globally enabled.
 */
enabled: boolean; 
/**
 * Cooldown between successive hotkey triggers (milliseconds).
 */
cooldown_ms: number; 
/**
 * Key binding strings (e.g. "F6", "Shift+F6").
 */
next_preset: string; prev_preset: string; toggle_overlay: string; next_variant: string; prev_variant: string }
export type IgnoredConflict = { id: string; game_id: string; object_id: string; object_name: string | null; mod_ids: string; mod_names?: string[]; created_at: string }
/**
 * DTO returned to the frontend for import queue display.
 */
export type ImportJobDto = { id: string; download_id: string | null; game_id: string | null; archive_path: string; status: string; match_category: string | null; match_entry_key: string | null; match_alias_name: string | null; match_confidence: number | null; match_reason: string | null; placed_path: string | null; error_msg: string | null; is_duplicate: boolean; created_at: string; updated_at: string }
export type IniDocument = { file_path: string; raw_lines: string[]; variables: IniVariable[]; key_bindings: KeyBinding[]; had_bom: boolean; newline_style: NewlineStyle; mode: IniReadMode }
export type IniFileEntry = { filename: string; path: string }
export type IniLineUpdate = { line_idx: number; content: string }
export type IniReadMode = "Structured" | "RawFallback"
export type IniVariable = { name: string; value: string; line_idx: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type KeyBinding = { section_name: string; key: string | null; back: string | null; key_line_idx: number; back_line_idx: number }
/**
 * KeyViewer-specific configuration — persisted in AppSettings.
 */
export type KeyViewerConfig = { 
/**
 * Whether KeyViewer generation is enabled.
 */
enabled: boolean }
export type MatchCheckResult = { matchedName: string | null; matchScorePct: number; targetScorePct: number; isMatch: boolean; confidence: string }
/**
 * Matched DB entry returned to frontend with resolved absolute thumbnail path.
 */
export type MatchedDbEntry = { name: string; matched_entry_key: string | null; matched_alias_name: string | null; object_type: string; tags: string[]; metadata: JsonValue | null; thumbnail_path: string | null; match_level: string; match_confidence: string; match_detail: string }
/**
 * The kind of member in a collection.
 */
export type MemberKind = "mod" | "nested" | "object" | "root"
/**
 * Errors specific to Metadata operations.
 */
export type MetadataError = { Security: string } | { NotFound: string } | { Io: string } | { Db: string } | { Validation: string }
/**
 * Result of a metadata sync check
 */
export type MetadataSyncResult = { updated: boolean; version: number | null }
/**
 * The standard mod metadata structure stored in `info.json`.
 * 
 * Matches the default template from Epic 4 cross-cutting requirements:
 * `{ actual_name, author, description, version, tags, is_safe, is_favorite }`
 */
export type ModInfo = { actual_name?: string; author?: string; description?: string; version?: string; tags?: string[]; is_safe?: boolean; is_favorite?: boolean; is_pinned?: boolean; is_auto_sync?: boolean; preset_name?: string[]; metadata?: Partial<{ [key in string]: string }> }
/**
 * Partial update struct — only fields that are `Some` will be updated.
 */
export type ModInfoUpdate = { actual_name: string | null; author: string | null; description: string | null; version: string | null; tags: string[] | null; tags_add: string[] | null; tags_remove: string[] | null; is_safe: boolean | null; is_favorite: boolean | null; is_pinned: boolean | null; is_auto_sync: boolean | null; preset_name_add: string[] | null; preset_name_remove: string[] | null; metadata: Partial<{ [key in string]: string }> | null }
export type MoveModsToObjectInput = { game_id: string; folder_paths: string[]; target_object_id: string; target_subpath: string | null; status: string | null }
export type NewlineStyle = "Lf" | "CrLf"
/**
 * `Default` is the unfiltered, safe-mode-off query. Callers spell out only
 * the axes they actually constrain — the full seven-field literal was written
 * out at twenty sites.
 */
export type ObjectFilter = { game_id: string; search_query: string | null; object_type: string | null; meta_filters: Partial<{ [key in string]: string[] }> | null; sort_by: string | null; status_filter: number | null }
export type ObjectSummary = { id: string; name: string; folder_path: string; matched_entry_key: string | null; matched_alias_name: string | null; matched_confidence: number | null; matched_reason: string | null; matched_source: string | null; object_type: string; sub_category: string | null; status: number; metadata: string; tags: string; hash_db: HashDbPayload | null; custom_skins: CustomSkinsPayload | null; is_pinned: boolean; is_auto_sync: boolean; thumbnail_path: string | null; created_at: string | null; mod_count: number; enabled_count: number; is_object_disabled: boolean; has_naming_conflict: boolean; active_mod_paths: string | null }
/**
 * Errors specific to Pin operations.
 */
export type PinError = { Db: string }
/**
 * Frontend-facing PIN status (no hashes leaked).
 */
export type PinStatus = { has_pin: boolean; is_locked: boolean; attempts_remaining: number; lockout_seconds_remaining: number }
export type PipelineTask = { id: string; game_id: string; task_type: string; status: TaskStatus; target_id: string | null; created_at: string; updated_at: string }
export type PreviewTreeNode = { kind: PreviewTreeNodeKind; id: string; name: string; path: string | null; object_id: string | null; node_type: string | null; is_enabled: boolean; is_effectively_active: boolean; inactive_reason: string | null; show_inactive_chip: boolean; status_kind: string | null; collapse_children: boolean; warnings: string[]; mod_count: number | null; children: PreviewTreeNode[] }
export type PreviewTreeNodeKind = "object" | "folder" | "mod"
export type ProjectedActiveRoot = { object_id: string; root_key: string; display_name: string; root_type: string; source_path: string; thumbnail_hint: string | null; warnings: string[]; is_missing: boolean }
export type ProjectedCollectionState = { object_states: ProjectedObjectState[]; active_roots: ProjectedActiveRoot[]; summary: ProjectedStateSummary }
export type ProjectedObjectState = { object_id: string; display_name: string; path_key: string; is_enabled: boolean; active_root_count: number }
export type ProjectedStateSummary = { object_count: number; enabled_object_count: number; active_root_count: number; missing_root_count: number }
export type RandomModProposal = { object_id: string; object_name: string; mod_id: string; name: string; thumbnail_path: string | null; folder_path: string }
/**
 * A recently indexed mod for the activity widget.
 */
export type RecentMod = { id: string; name: string; game_name: string; object_name: string | null; indexed_at: string | null }
export type RecoveryAction = "RETRY" | "ROLLBACK" | "IGNORE"
export type RenameResult = { old_path: string; new_path: string; new_name: string; collection_impact: CollectionReferenceImpact }
export type ResolutionAction = "keepA" | "keepB" | "ignore" | "hardlink"
export type ResolutionError = { groupId: string; action: ResolutionAction; message: string }
export type ResolutionRequest = { groupId: string; action: ResolutionAction; folderA: string; folderB: string }
export type ResolutionSummary = { total: number; successful: number; failed: number; errors: ResolutionError[] }
export type SafeModeConfig = { enabled: boolean; pin_hash: string | null; recovery_code_hash: string | null; keywords: string[]; force_exclusive_mode: boolean; failed_attempts: number | null; lockout_until_ts: number | null }
/**
 * Progress events streamed to frontend via `Channel<ScanEvent>`.
 */
export type ScanEvent = 
/**
 * Scan has started, includes total folder count.
 */
{ event: "started"; data: { totalFolders: number } } | 
/**
 * One folder has been processed.
 */
{ event: "progress"; data: { current: number; total: number; folderName: string; elapsedMs: number; etaMs: number } } | 
/**
 * A match was found for a folder.
 */
{ event: "matched"; data: { folderName: string; objectName: string; confidence: string } } | 
/**
 * Scan is complete.
 */
{ event: "finished"; data: { matched: number; unmatched: number } }
/**
 * A single preview item returned by scan_preview (before user confirms).
 */
export type ScanPreviewItem = { folderPath: string; displayName: string; isDisabled: boolean; matchedEntryKey: string | null; matchedAliasName: string | null; matchLevel: string; confidence: string; confidenceScore: number; matchDetail: string | null; detectedSkin: string | null; objectType: string | null; thumbnailPath: string | null; 
/**
 * Tags from MasterDB entry (JSON array string)
 */
tagsJson: string | null; 
/**
 * Metadata from MasterDB entry (JSON object string)
 */
metadataJson: string | null; 
/**
 * Whether this mod already exists in DB
 */
alreadyInDb: boolean; 
/**
 * Whether this mod already has an object_id assigned
 */
alreadyMatched: boolean; 
/**
 * Top-k scored candidates from the matcher (name + percentage).
 */
scoredCandidates: ScoredCandidate[]; 
/**
 * Optional hash_db from MasterDB entry (JSON object string)
 */
hashDbJson: string | null; 
/**
 * Optional custom_skins from MasterDB entry (JSON array string)
 */
customSkinsJson: string | null; dbThumbnail: string | null }
/**
 * Errors from scanning the mods tree: walking folders, matching against the
 * MasterDB, duplicate detection, and committing a scan into the index.
 */
export type ScannerError = { PathNotFound: { path: string } } | { NotADirectory: { path: string } } | { PathEscape: { path: string } } | { Parse: { what: string; detail: string } } | { Network: string } | { Io: string } | { Db: string } | { Validation: string }
/**
 * A lightweight scored candidate for the frontend dropdown.
 */
export type ScoredCandidate = { name: string; objectType: string; scorePct: number }
export type SearchResultEntry = { item: DbEntry; score: number }
export type SyncResult = { totalScanned: number; newMods: number; updatedMods: number; deletedMods: number; newObjects: number; collisions: CollisionInfo[] }
export type TAURI_CHANNEL<TSend> = null
export type TaskStatus = "PENDING" | "COMPLETED" | "FAILED"
export type ThemeConfig = { colors: Partial<{ [key in string]: string }>; glass: Partial<{ [key in string]: string }> }
export type ThemeMetadata = { id: string; label: string }
/**
 * Metadata stored alongside each trashed item for restore.
 */
export type TrashMetadata = { 
/**
 * Unique ID for this trash entry
 */
id: string; 
/**
 * Original absolute path before deletion
 */
original_path: string; 
/**
 * Display name of the mod folder
 */
original_name: string; 
/**
 * ISO 8601 timestamp of deletion
 */
deleted_at: string; 
/**
 * Total size in bytes
 */
size_bytes: number; 
/**
 * Associated game_id (for DB cleanup)
 */
game_id: string | null }
export type UpdateObjectInput = { name: string | null; object_type: string | null; sub_category: string | null; status: number | null; metadata: JsonValue | null; hash_db: HashDbPayload | null; custom_skins: CustomSkinsPayload | null; thumbnail_path: string | null; is_auto_sync: boolean | null; is_pinned: boolean | null; tags: string[] | null }
export type WhitelistEntry = { id: string; folderAId: string; folderBId: string; folderAName: string; folderBName: string; reason: string; ignoredAt: string }
export type WorkspaceCapabilities = { can_toggle: boolean; can_rename: boolean; can_delete: boolean; can_move: boolean; can_toggle_safe: boolean; can_sync: boolean; can_enable_only_this: boolean; can_pin: boolean; can_edit_metadata: boolean; can_reveal_in_explorer: boolean; can_move_category: boolean; can_open_in_explorer: boolean }
export type WorkspaceDisplayMode = "container_folder" | "mod_pack" | "variant" | "flat_mod" | "internal_assets" | "unknown"
export type WorkspaceExplorer = { self_node_type: string | null; self_node_kind: WorkspaceNodeKind; self_display_mode: WorkspaceDisplayMode; self_type_chip: WorkspaceTypeChip | null; self_is_mod: boolean; self_is_enabled: boolean; self_is_effectively_active: boolean; self_owner_object_id: string | null; self_owner_object_folder_path: string | null; self_classification_reasons: string[]; children: WorkspaceExplorerNode[]; conflicts: ConflictGroup[]; ancestor_disabled_by: string | null; ancestor_disabled_path: string | null; inactive_reason: WorkspaceReason | null }
export type WorkspaceExplorerNode = { node_type: string; classification_reasons: string[]; id: string | null; owner_object_id: string | null; owner_object_folder_path: string | null; name: string; folder_name: string; path: string; is_enabled: boolean; is_directory: boolean; thumbnail_path: string | null; modified_at: number; size_bytes: number; has_info_json: boolean; is_favorite: boolean; is_misplaced: boolean; is_safe: boolean; metadata: Partial<{ [key in string]: string }> | null; category: string | null; conflict_group_id: string | null; conflict_state: string | null; warnings: string[]; node_kind: WorkspaceNodeKind; display_mode: WorkspaceDisplayMode; type_chip: WorkspaceTypeChip | null; display_name: string; is_effectively_active: boolean; ancestor_disabled: boolean; inactive_reason: WorkspaceReason | null; warning_state: WorkspaceWarningState; primary_warning: WorkspaceWarning | null; switch_state: WorkspaceSwitchState; switch_reason: WorkspaceReason | null; switch_policy_key: WorkspaceSwitchPolicyKey; capabilities: WorkspaceCapabilities; can_navigate: boolean }
export type WorkspaceImageSummary = { image_count: number; primary_image_path: string | null }
export type WorkspaceImpact = { rewrites: WorkspacePathRewrite[]; changed_object_ids: string[]; changed_folder_paths: string[]; refresh_scopes: WorkspaceRefreshScope[]; warnings: string[] }
export type WorkspaceIniSummary = { file_count: number; file_names: string[] }
export type WorkspaceModInfoSummary = { actual_name: string; author: string; version: string; description: string; is_safe: boolean; is_favorite: boolean; has_info_json: boolean }
export type WorkspaceMoveTarget = { object_id: string; object_name: string; object_folder_path: string; target_subpath: string | null; display_path: string; depth: number }
export type WorkspaceNode = WorkspaceExplorerNode | WorkspaceObjectNode
export type WorkspaceNodeKind = "object" | "container" | "terminal_mod" | "inactive_branch"
export type WorkspaceObjectNode = ({ id: string; name: string; folder_path: string; matched_entry_key: string | null; matched_alias_name: string | null; matched_confidence: number | null; matched_reason: string | null; matched_source: string | null; object_type: string; sub_category: string | null; status: number; metadata: string; tags: string; hash_db: HashDbPayload | null; custom_skins: CustomSkinsPayload | null; is_pinned: boolean; is_auto_sync: boolean; thumbnail_path: string | null; created_at: string | null; mod_count: number; enabled_count: number; is_object_disabled: boolean; has_naming_conflict: boolean; active_mod_paths: string | null }) & { node_kind: WorkspaceNodeKind; display_mode: WorkspaceDisplayMode; type_chip: WorkspaceTypeChip | null; display_name: string; is_effectively_active: boolean; inactive_reason: WorkspaceReason | null; warning_state: WorkspaceWarningState; primary_warning: WorkspaceWarning | null; switch_state: WorkspaceSwitchState; switch_reason: WorkspaceReason | null; switch_policy_key: WorkspaceSwitchPolicyKey; capabilities: WorkspaceCapabilities }
export type WorkspacePathRewrite = { old_path: string; new_path: string }
export type WorkspacePreview = { selected_path: string | null; selected_node: WorkspaceNode | null; is_flat_mod_root: boolean; display_title: string | null; display_subtitle: string | null; mod_info_summary: WorkspaceModInfoSummary | null; ini_summary: WorkspaceIniSummary | null; image_summary: WorkspaceImageSummary | null; warning_summary: WorkspaceWarningSummary }
export type WorkspaceReason = { code: WorkspaceReasonCode; args: Partial<{ [key in string]: string }> }
export type WorkspaceReasonCode = "disabled_by_container" | "object_folder_disabled"
export type WorkspaceRefreshScope = "workspaceChanged" | "objectRowsChanged" | "folderStructureChanged" | "previewChanged" | "conflictsChanged" | "corridorChanged" | "collectionsChanged" | "dashboardChanged" | "activeKeybindingsChanged"
export type WorkspaceRuntime = { game_id: string; safe_mode: boolean; source_state: WorkspaceSourceState }
export type WorkspaceSelection = { selected_object_folder_path: string | null; explorer_sub_path: string | null; selected_mod_path: string | null; current_path: string[]; reconciliation_status: WorkspaceSelectionReconciliationStatus; reconciliation_reason: WorkspaceSelectionReconciliationReason | null; affected_paths: string[] }
export type WorkspaceSelectionReconciliationReason = "missing_object_root" | "missing_explorer_path" | "missing_mod_path" | "corridor_mismatch" | "source_unavailable"
export type WorkspaceSelectionReconciliationStatus = "unchanged" | "fallback" | "cleared"
export type WorkspaceSourceState = { status: WorkspaceSourceStatus; message: string | null }
export type WorkspaceSourceStatus = "available" | "unavailable"
export type WorkspaceSwitchDuplicate = { mod_id: string; object_id: string; folder_path: string; actual_name: string; is_variant: boolean; parent_path: string }
export type WorkspaceSwitchInput = { game_id: string; target: WorkspaceSwitchTarget; desired_enabled: boolean; resolution: WorkspaceSwitchResolution; origin_surface: WorkspaceSwitchOriginSurface }
export type WorkspaceSwitchOriginSurface = "folder_grid" | "preview" | "object_list" | "collections" | "corridor"
export type WorkspaceSwitchPolicyKey = "mod" | "object" | "blocked"
export type WorkspaceSwitchResolution = "normal" | "force_enable" | "enable_only_this" | "enable_parent_then_continue"
export type WorkspaceSwitchResult = { status: WorkspaceSwitchStatus; primary_path: string | null; changed_folder_paths: string[]; changed_object_ids: string[]; duplicates: WorkspaceSwitchDuplicate[]; impact: WorkspaceImpact }
export type WorkspaceSwitchState = "enabled" | "disabled" | "effectively_disabled" | "blocked_by_ancestor"
export type WorkspaceSwitchStatus = "applied" | "requires_duplicate_resolution" | "noop"
export type WorkspaceSwitchTarget = { kind: WorkspaceSwitchTargetKind; value: string }
export type WorkspaceSwitchTargetKind = "mod_path" | "object_id"
export type WorkspaceTypeChip = "mod_pack" | "variant" | "flat_mod"
export type WorkspaceViewModel = { objects: WorkspaceObjectNode[]; explorer: WorkspaceExplorer; preview: WorkspacePreview; selection: WorkspaceSelection; runtime: WorkspaceRuntime }
export type WorkspaceViewModelInput = { filter: ObjectFilter; selected_object_folder_path: string | null; explorer_sub_path: string | null; selected_mod_path: string | null }
export type WorkspaceWarning = { code: WorkspaceWarningCode; args: Partial<{ [key in string]: string }>; state: WorkspaceWarningState }
export type WorkspaceWarningCode = "folder_warning" | "inactive_reason" | "naming_conflict"
export type WorkspaceWarningState = "none" | "warning"
export type WorkspaceWarningSummary = { state: WorkspaceWarningState; messages: WorkspaceWarning[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
