use super::*;

// ─── KeyViewer.ini Generation ────────────────────────────────────────────────

#[test]
fn keyviewer_ini_contains_header() {
    let ini = generate_keyviewer_ini(&[], "F7", ".emmm_data/keybinds/active");
    assert!(ini.contains(";   KeyViewer.ini — Auto-generated by EMMM"));
}

#[test]
fn keyviewer_ini_contains_toggle_key() {
    let ini = generate_keyviewer_ini(&[], "F7", ".emmm_data/keybinds/active");
    // New key section uses cycle type
    assert!(ini.contains("[KeyEMMM_Toggle]"));
    assert!(ini.contains("key = F7"));
    assert!(ini.contains("type = cycle"));
    assert!(ini.contains("$kv_active = 0, 1"));
}

#[test]
fn keyviewer_ini_contains_sentinel_sections() {
    let matches = vec![make_match_result("Albedo", &["aabb1111"])];
    let ini = generate_keyviewer_ini(&matches, "F7", ".emmm_data/keybinds/active");
    // New prefix is TextureOverride_EMM_ with hyphen/space → underscore
    assert!(ini.contains("[TextureOverride_EMM_Albedo_S0]"));
    assert!(ini.contains("hash = aabb1111"));
    assert!(ini.contains("$kv_has_active = 1"));
    assert!(ini.contains("$kv_active_code = 0xaabb1111"));
    assert!(ini.contains("$kv_last_seen = time"));
}

#[test]
fn keyviewer_ini_contains_present_section() {
    let ini = generate_keyviewer_ini(&[], "F7", ".emmm_data/keybinds/active");
    assert!(ini.contains("[Present]"));
    // Reset flag via post
    assert!(ini.contains("post $kv_has_active = 0"));
    // Stale detection at 1.5s (not 0.5s)
    assert!(ini.contains("if time - $kv_last_seen > 1.5"));
    // Delegate to render command list
    assert!(ini.contains("run = CommandList_EMM_Render"));
}

#[test]
fn keyviewer_ini_uses_help_ini_pipeline() {
    let matches = vec![make_match_result("Albedo", &["aabb1111"])];
    let ini = generate_keyviewer_ini(&matches, "F7", ".emmm_data/keybinds/active");
    // Must use help.ini notification pipeline — NOT ps-t100
    assert!(!ini.contains("ps-t100"));
    assert!(ini.contains(
        r"pre Resource\ShaderFixes\help.ini\Notification = ref ResourceKeyViewer_aabb1111"
    ));
    assert!(ini.contains(r"pre Resource\ShaderFixes\help.ini\NotificationParams = ref ResourceBox"));
    assert!(ini.contains(r"pre run = CustomShader\ShaderFixes\help.ini\FormatText"));
    assert!(ini.contains("notification_timeout = 1000000000.0"));
    // OFF path must null the notification
    assert!(ini.contains(r"Resource\ShaderFixes\help.ini\Notification = null"));
}

#[test]
fn keyviewer_ini_single_decision_tree_no_dual_draw() {
    let matches = vec![make_match_result("Albedo", &["aabb1111"])];
    let ini = generate_keyviewer_ini(&matches, "F7", ".emmm_data/keybinds/active");
    // Status banner shown in else branch, NOT in separate draw call
    assert!(ini.contains("ref ResourceStatus"));
    // There must be NO parallel dual-draw command lists
    assert!(!ini.contains("KV_DrawStatus"));
    assert!(!ini.contains("KV_DrawKeybinds"));
}

#[test]
fn keyviewer_ini_contains_resource_sections() {
    let matches = vec![make_match_result("Albedo", &["aabb1111"])];
    let ini = generate_keyviewer_ini(&matches, "F7", ".emmm_data/keybinds/active");
    // New resource name is ResourceKeyViewer_HASH
    assert!(ini.contains("[ResourceKeyViewer_aabb1111]"));
    assert!(ini.contains("filename = .emmm_data/keybinds/active/aabb1111.txt"));
    // Correct type/format casing
    assert!(ini.contains("type = buffer"));
    assert!(ini.contains("format = R8_UINT"));
    // ResourceStatus section is present
    assert!(ini.contains("[ResourceStatus]"));
    assert!(ini.contains("filename = .emmm_data/status/runtime_status.txt"));
    // ResourceBox section is present
    assert!(ini.contains("[ResourceBox]"));
    assert!(ini.contains("type = StructuredBuffer"));
}

#[test]
fn keyviewer_ini_has_fallback_resource() {
    let ini = generate_keyviewer_ini(&[], "F7", "keybinds");
    assert!(ini.contains("[ResourceKeyViewer_Fallback]"));
    assert!(ini.contains("filename = keybinds/_fallback.txt"));
}

#[test]
fn keyviewer_ini_handles_spaces_in_names() {
    let matches = vec![make_match_result("Arataki Itto", &["cc112233"])];
    let ini = generate_keyviewer_ini(&matches, "F7", "keybinds");
    // Spaces (and hyphens) replaced with underscores in section name
    assert!(ini.contains("[TextureOverride_EMM_Arataki_Itto_S0]"));
}

#[test]
fn keyviewer_ini_global_variables() {
    let ini = generate_keyviewer_ini(&[], "F7", "keybinds");
    // New global variable names
    assert!(ini.contains("global $kv_active = 0"));
    assert!(ini.contains("global $kv_has_active = 0"));
    assert!(ini.contains("global $kv_active_code = 0"));
    assert!(ini.contains("global $kv_last_seen = 0"));
    // Old names must NOT appear
    assert!(!ini.contains("$kv_visible"));
    assert!(!ini.contains("$kv_detection_frame"));
}
