use std::path::Path;

use crate::domain::errors::AppError;
use crate::domain::models::GameType;
use crate::services::keyviewer::matcher::MatchResult;

use super::atomic::atomic_write;

fn text_api_namespace(game_type: GameType) -> Result<&'static str, AppError> {
    match game_type {
        GameType::GIMI => Ok("GIMIv8"),
        GameType::SRMI => Ok("SRMIv1"),
        GameType::WWMI => Ok("WWMIv1"),
        GameType::ZZMI => Ok("ZZMIv1"),
        GameType::EFMI => Err(AppError::Validation(
            "KeyViewer text overlay is not supported by the installed EFMI profile".to_string(),
        )),
    }
}

fn section_component(name: &str) -> String {
    name.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character
            } else {
                '_'
            }
        })
        .collect()
}

fn validate_sentinel(hash: &str) -> Result<(), AppError> {
    if hash.len() == 8 && hash.chars().all(|character| character.is_ascii_hexdigit()) {
        return Ok(());
    }
    Err(AppError::Validation(format!(
        "KeyViewer sentinel must be an 8-digit resource hash: {hash}"
    )))
}

/// Generate a package-portable KeyViewer config using the official text API.
/// Resource filenames are relative to `.emmm_data/KeyViewer.ini`.
pub fn generate_keyviewer_ini(
    matches: &[MatchResult],
    toggle_key: &str,
    game_type: GameType,
) -> Result<String, AppError> {
    let namespace = text_api_namespace(game_type)?;
    for sentinel in matches
        .iter()
        .flat_map(|result| result.sentinel_hashes.iter())
    {
        validate_sentinel(sentinel)?;
    }

    let mut lines = vec![
        "; =================================================================".to_string(),
        ";   KeyViewer.ini — Auto-generated by EMMM".to_string(),
        ";   Do not edit manually.".to_string(),
        "; =================================================================".to_string(),
        String::new(),
        "[Constants]".to_string(),
        "global $kv_active = 0".to_string(),
        "global $kv_active_code = 0".to_string(),
        "global $kv_last_seen = 0".to_string(),
        String::new(),
        "[KeyEMMM_Toggle]".to_string(),
        format!("key = {}", toggle_key.replace('+', " ")),
        "type = cycle".to_string(),
        "$kv_active = 0, 1".to_string(),
        String::new(),
    ];

    for result in matches {
        for (index, sentinel) in result.sentinel_hashes.iter().enumerate() {
            lines.push(format!(
                "[TextureOverride_EMM_{}_S{index}]",
                section_component(&result.object_name)
            ));
            lines.push(format!("hash = {sentinel}"));
            lines.push(format!("$kv_active_code = 0x{sentinel}"));
            lines.push("$kv_last_seen = time".to_string());
            lines.push(String::new());
        }
    }

    lines.extend([
        "[Present]".to_string(),
        "if time - $kv_last_seen > 1.5".to_string(),
        "    $kv_active_code = 0".to_string(),
        "endif".to_string(),
        "run = CommandList_EMM_Render".to_string(),
        String::new(),
        "[CommandList_EMM_Render]".to_string(),
        "if $kv_active == 1".to_string(),
        format!("    Resource\\{namespace}\\Text = ref ResourceStatus"),
    ]);

    for result in matches {
        for sentinel in &result.sentinel_hashes {
            lines.push(format!("    if $kv_active_code == 0x{sentinel}"));
            lines.push(format!(
                "        Resource\\{namespace}\\Text = ref ResourceKeyViewer_{sentinel}"
            ));
            lines.push("    endif".to_string());
        }
    }

    lines.extend([
        format!("    Resource\\{namespace}\\TextParams = ref ResourceBox"),
        format!("    run = CommandList\\{namespace}\\PrintText"),
        "endif".to_string(),
        String::new(),
        "[ResourceBox]".to_string(),
        "type = StructuredBuffer".to_string(),
        "array = 1".to_string(),
        "data = R32_FLOAT  -0.97 -1 1 1  0 0.55 0.75 1  0 0 0 0.99  0.01 0.01  1 2  0  1.0"
            .to_string(),
        String::new(),
        "[ResourceStatus]".to_string(),
        "type = buffer".to_string(),
        "format = R8_UINT".to_string(),
        "filename = status/runtime_status.txt".to_string(),
        String::new(),
    ]);

    for result in matches {
        for sentinel in &result.sentinel_hashes {
            lines.push(format!("[ResourceKeyViewer_{sentinel}]"));
            lines.push("type = buffer".to_string());
            lines.push("format = R8_UINT".to_string());
            lines.push(format!("filename = keybinds/active/{sentinel}.txt"));
            lines.push(String::new());
        }
    }

    Ok(lines.join("\n"))
}

pub fn write_keyviewer_ini(
    output_path: &Path,
    matches: &[MatchResult],
    toggle_key: &str,
    game_type: GameType,
) -> Result<(), AppError> {
    let content = generate_keyviewer_ini(matches, toggle_key, game_type)?;
    atomic_write(output_path, &content)
}
