use std::path::Path;

use crate::domain::errors::AppError;
use crate::services::keyviewer::matcher::MatchResult;

use super::atomic::atomic_write;

// ─── KeyViewer.ini Generation ────────────────────────────────────────────────

/// Generate KeyViewer.ini content for 3DMigoto runtime overlay.
///
/// Uses the `help.ini` (3DMigoto FormatText) pipeline exclusively — the only
/// text renderer available without a custom shader. All text overlays are sent
/// via `pre Resource\ShaderFixes\help.ini\Notification` + `FormatText`.
///
/// Design principles (aligned with reference _KeyViewer):
/// - `$kv_has_active` reset per-frame via `post` in [Present]; set by TextureOverride on hit
/// - help.ini has ONE Notification slot — SINGLE decision tree: KeyViewer > Status
/// - `notification_timeout` set to ~infinity for persistence (no auto-hide)
/// - Stale detection at 1.5s (not 0.5s) to prevent camera-pan flicker
/// - `type = cycle` toggle key for sticky on/off
/// - All buffer resources: `type = buffer` + `format = R8_UINT` (lowercase, correct case)
pub fn generate_keyviewer_ini(
    matches: &[MatchResult],
    toggle_key: &str,
    keybinds_dir: &str,
) -> String {
    let mut lines: Vec<String> = Vec::new();

    // ── Header ───────────────────────────────────────────────────────────────
    lines.push("; =================================================================".to_string());
    lines.push(";   KeyViewer.ini — Auto-generated by EMMM".to_string());
    lines
        .push(";   Do NOT edit manually. Regenerated on mod/preset/safe-mode changes.".to_string());
    lines.push("; =================================================================".to_string());
    lines.push(String::new());

    // ── Global state variables ─────────────────────────────────────────────
    // $kv_active      = 0|1   master overlay toggle
    // $kv_has_active  = 0|1   set by TextureOverride each frame; reset by post in [Present]
    // $kv_active_code = 0xH   hash of the currently detected object
    // $kv_last_seen   = time  float timestamp of last successful hash detection
    lines.push("[Constants]".to_string());
    lines.push("global $kv_active = 0".to_string());
    lines.push("global $kv_has_active = 0".to_string());
    lines.push("global $kv_active_code = 0".to_string());
    lines.push("global $kv_last_seen = 0".to_string());
    lines.push(String::new());

    // ── Toggle key ─────────────────────────────────────────────────────────
    lines.push("; Press to show/hide the overlay".to_string());
    lines.push("[KeyEMMM_Toggle]".to_string());
    lines.push(format!("key = {toggle_key}"));
    lines.push("type = cycle".to_string());
    lines.push("$kv_active = 0, 1".to_string());
    lines.push(String::new());

    // ── TextureOverride sections (per sentinel hash) ────────────────────────
    // Fire every frame the hash is on screen. Sets $kv_has_active + $kv_active_code.
    // [Present] resets $kv_has_active via `post` before these run, so the value is
    // always fresh: 0 means nothing matched this frame.
    if !matches.is_empty() {
        lines.push(
            "; ─── Hash detection — fires when object is on screen ───────────────────".to_string(),
        );
        for match_result in matches {
            for (i, sentinel) in match_result.sentinel_hashes.iter().enumerate() {
                let section_name = format!(
                    "TextureOverride_EMM_{}_S{}",
                    match_result.object_name.replace([' ', '-'], "_"),
                    i
                );
                lines.push(format!("[{section_name}]"));
                lines.push(format!("hash = {sentinel}"));
                lines.push("$kv_has_active = 1".to_string());
                lines.push(format!("$kv_active_code = 0x{sentinel}"));
                lines.push("$kv_last_seen = time".to_string());
                lines.push(String::new());
            }
        }
    }

    // ── Present (per-frame driver) ─────────────────────────────────────────
    lines.push("[Present]".to_string());
    lines.push(
        "; Reset detection flag each frame. TextureOverride re-sets it if hash hits.".to_string(),
    );
    lines.push("post $kv_has_active = 0".to_string());
    lines.push(String::new());
    lines.push(
        "; Stale detection: clear active_code if no hash seen for > 1.5 seconds.".to_string(),
    );
    lines.push("; 1.5s threshold prevents flicker during camera panning.".to_string());
    lines.push("if time - $kv_last_seen > 1.5".to_string());
    lines.push("    $kv_active_code = 0".to_string());
    lines.push("endif".to_string());
    lines.push(String::new());
    lines.push("run = CommandList_EMM_Render".to_string());
    lines.push(String::new());

    // ── Render command list ─────────────────────────────────────────────────
    // SINGLE DECISION TREE. help.ini has exactly one Notification slot.
    // Writing it twice (last write wins) causes overlay conflicts.
    // Rule: if character is active → show KeyViewer; else → show Status banner.
    lines.push(
        "; ─── Render logic — help.ini pipeline ────────────────────────────────────".to_string(),
    );
    lines.push(
        "; help.ini supports ONE ResourceNotification slot — single decision tree.".to_string(),
    );
    lines.push("; Priority: per-character KeyViewer > global Status banner.".to_string());
    lines.push("[CommandList_EMM_Render]".to_string());
    lines.push("if $kv_active == 1".to_string());
    lines.push(String::new());
    lines.push("    if $kv_has_active == 1".to_string());
    lines.push(
        "        ; ── Character detected: show per-character keybind text ──────────".to_string(),
    );
    for match_result in matches {
        for sentinel in &match_result.sentinel_hashes {
            let resource_name = format!("ResourceKeyViewer_{sentinel}");
            lines.push(format!("        if $kv_active_code == 0x{sentinel}"));
            lines.push(format!(
                "            pre Resource\\ShaderFixes\\help.ini\\Notification = ref {resource_name}"
            ));
            lines.push("        endif".to_string());
        }
    }
    lines.push("    else".to_string());
    lines.push(
        "        ; ── No character detected: show status banner ──────────────────".to_string(),
    );
    lines.push(
        "        pre Resource\\ShaderFixes\\help.ini\\Notification = ref ResourceStatus"
            .to_string(),
    );
    lines.push("    endif".to_string());
    lines.push(String::new());
    lines.push(
        "    pre Resource\\ShaderFixes\\help.ini\\NotificationParams = ref ResourceBox".to_string(),
    );
    lines.push("    pre run = CustomShader\\ShaderFixes\\help.ini\\FormatText".to_string());
    lines.push("    $\\ShaderFixes\\help.ini\\notification_timeout = 1000000000.0".to_string());
    lines.push(String::new());
    lines.push("else".to_string());
    lines.push(
        "    ; Overlay toggled OFF — null the notification slot so nothing renders".to_string(),
    );
    lines.push("    Resource\\ShaderFixes\\help.ini\\Notification = null".to_string());
    lines.push("endif".to_string());
    lines.push(String::new());

    // ── ResourceBox — overlay layout params ───────────────────────────────
    // Matches reference ResourceArea format (single-line StructuredBuffer):
    //   pos(x y x2 y2)  textRGBA  bgRGBA  border(x y)  align(h v)  anchor  scale
    lines.push(
        "; ─── Layout/styling for the overlay box ──────────────────────────────────".to_string(),
    );
    lines.push("[ResourceBox]".to_string());
    lines.push("type = StructuredBuffer".to_string());
    lines.push("array = 1".to_string());
    lines.push("data = R32_FLOAT  -0.97 -1 1 1      0 0.55 0.75 1    0 0 0 0.99   0.01 0.01     1 2   0  1.0".to_string());
    lines.push(String::new());

    // ── ResourceStatus — status banner text ────────────────────────────────
    lines.push("; Status banner (shown when no character is active)".to_string());
    lines.push("[ResourceStatus]".to_string());
    lines.push("type = buffer".to_string());
    lines.push("format = R8_UINT".to_string());
    lines.push("filename = .emmm_data/status/runtime_status.txt".to_string());
    lines.push(String::new());

    // ── Per-sentinel keybind text resources ───────────────────────────────
    lines.push(
        "; ─── Per-character keybind text resources ────────────────────────────────".to_string(),
    );
    for match_result in matches {
        for sentinel in &match_result.sentinel_hashes {
            lines.push(format!("[ResourceKeyViewer_{sentinel}]"));
            lines.push("type = buffer".to_string());
            lines.push("format = R8_UINT".to_string());
            lines.push(format!("filename = {keybinds_dir}/{sentinel}.txt"));
            lines.push(String::new());
        }
    }

    // Fallback (no matched hash, but $kv_has_active was 1 — shouldn't happen but safety net)
    lines.push("[ResourceKeyViewer_Fallback]".to_string());
    lines.push("type = buffer".to_string());
    lines.push("format = R8_UINT".to_string());
    lines.push(format!("filename = {keybinds_dir}/_fallback.txt"));
    lines.push(String::new());

    lines.join("\n")
}

/// Generate and write KeyViewer.ini atomically.
pub fn write_keyviewer_ini(
    output_path: &Path,
    matches: &[MatchResult],
    toggle_key: &str,
    keybinds_dir: &str,
) -> Result<(), AppError> {
    let content = generate_keyviewer_ini(matches, toggle_key, keybinds_dir);
    atomic_write(output_path, &content)
}
