import type { CollectionSummary, ProjectedCollectionState } from '@/shared/api/tauri/bindings.gen';
export const demoCollections: CollectionSummary[] = [
  {
    id: 'demo-collection-story',
    name: 'Story Mode',
    is_safe: true,
    is_safety_classified: true,
    is_active: true,
    signature: 'demo-story-v1',
    updated_at: '2026-09-13T06:00:00Z',
    mod_count: 84,
  },
  {
    id: 'demo-collection-photo',
    name: 'Photo Session',
    is_safe: true,
    is_safety_classified: true,
    is_active: false,
    signature: 'demo-photo-v1',
    updated_at: '2026-09-12T06:00:00Z',
    mod_count: 31,
  },
  {
    id: 'demo-collection-exploration',
    name: 'Exploration Set',
    is_safe: true,
    is_safety_classified: true,
    is_active: false,
    signature: 'demo-exploration-v1',
    updated_at: '2026-09-11T08:00:00Z',
    mod_count: 18,
  },
];

export const demoProjectedState: ProjectedCollectionState = {
  object_states: [
    {
      object_id: 'demo-object-nekomata',
      display_name: 'Nekomata',
      path_key: 'characters/nekomata',
      is_enabled: true,
      active_root_count: 1,
    },
    {
      object_id: 'demo-object-lumina',
      display_name: 'Lumina Square',
      path_key: 'environment/lumina-square',
      is_enabled: true,
      active_root_count: 2,
    },
    {
      object_id: 'demo-object-interface',
      display_name: 'Interface',
      path_key: 'ui/interface',
      is_enabled: true,
      active_root_count: 1,
    },
  ],
  active_roots: [
    {
      object_id: 'demo-object-nekomata',
      root_key: 'characters/nekomata/streetwear',
      display_name: 'Streetwear',
      root_type: 'mod',
      source_path: 'Characters\\Nekomata\\Streetwear',
      thumbnail_hint: null,
      warnings: [],
      is_missing: false,
      is_safe: true,
      safety_source: 'demo',
    },
    {
      object_id: 'demo-object-lumina',
      root_key: 'environment/lumina-square/recolor',
      display_name: 'Lumina Square Recolor',
      root_type: 'mod',
      source_path: 'Environment\\Lumina Square\\Recolor',
      thumbnail_hint: null,
      warnings: [],
      is_missing: false,
      is_safe: true,
      safety_source: 'demo',
    },
    {
      object_id: 'demo-object-lumina',
      root_key: 'environment/lumina-square/rainy-evening',
      display_name: 'Rainy Evening',
      root_type: 'mod',
      source_path: 'Environment\\Lumina Square\\Rainy Evening',
      thumbnail_hint: null,
      warnings: [],
      is_missing: false,
      is_safe: true,
      safety_source: 'demo',
    },
    {
      object_id: 'demo-object-interface',
      root_key: 'ui/interface/minimal-hud',
      display_name: 'Minimal HUD',
      root_type: 'mod',
      source_path: 'UI\\Interface\\Minimal HUD',
      thumbnail_hint: null,
      warnings: [],
      is_missing: false,
      is_safe: true,
      safety_source: 'demo',
    },
  ],
  summary: {
    object_count: 3,
    enabled_object_count: 3,
    active_root_count: 4,
    missing_root_count: 0,
  },
};
