import type { CollectionPreview } from '@/shared/api/tauri/bindings.gen';
import { demoCollections, demoProjectedState } from './collectionData';
export function getDemoCollectionPreview(collectionId: string): CollectionPreview {
  const collection = demoCollections.find((item) => item.id === collectionId) ?? demoCollections[0];
  return {
    collection,
    tree_nodes: [
      {
        kind: 'object',
        id: 'demo-object-nekomata',
        name: 'Nekomata',
        path: 'Characters\\Nekomata',
        object_id: 'demo-object-nekomata',
        node_type: 'character',
        is_enabled: true,
        is_effectively_active: true,
        inactive_reason: null,
        show_inactive_chip: false,
        status_kind: null,
        collapse_children: false,
        warnings: [],
        mod_count: 2,
        children: [
          {
            kind: 'mod',
            id: 'demo-mod-1',
            name: 'Nekomata Streetwear',
            path: 'Characters\\Nekomata\\Streetwear',
            object_id: 'demo-object-nekomata',
            node_type: 'mod',
            is_enabled: true,
            is_effectively_active: true,
            inactive_reason: null,
            show_inactive_chip: false,
            status_kind: null,
            collapse_children: false,
            warnings: [],
            mod_count: null,
            children: [],
          },
          {
            kind: 'mod',
            id: 'demo-mod-summer',
            name: 'Summer Palette',
            path: 'Characters\\Nekomata\\Summer Palette',
            object_id: 'demo-object-nekomata',
            node_type: 'mod',
            is_enabled: false,
            is_effectively_active: false,
            inactive_reason: 'Disabled',
            show_inactive_chip: true,
            status_kind: null,
            collapse_children: false,
            warnings: [],
            mod_count: null,
            children: [],
          },
        ],
      },
      {
        kind: 'object',
        id: 'demo-object-lumina',
        name: 'Lumina Square',
        path: 'Environment\\Lumina Square',
        object_id: 'demo-object-lumina',
        node_type: 'environment',
        is_enabled: true,
        is_effectively_active: true,
        inactive_reason: null,
        show_inactive_chip: false,
        status_kind: null,
        collapse_children: false,
        warnings: [],
        mod_count: 2,
        children: [
          {
            kind: 'mod',
            id: 'demo-mod-lumina-recolor',
            name: 'Lumina Square Recolor',
            path: 'Environment\\Lumina Square\\Recolor',
            object_id: 'demo-object-lumina',
            node_type: 'mod',
            is_enabled: true,
            is_effectively_active: true,
            inactive_reason: null,
            show_inactive_chip: false,
            status_kind: null,
            collapse_children: false,
            warnings: [],
            mod_count: null,
            children: [],
          },
          {
            kind: 'mod',
            id: 'demo-mod-rainy-evening',
            name: 'Rainy Evening',
            path: 'Environment\\Lumina Square\\Rainy Evening',
            object_id: 'demo-object-lumina',
            node_type: 'mod',
            is_enabled: true,
            is_effectively_active: true,
            inactive_reason: null,
            show_inactive_chip: false,
            status_kind: null,
            collapse_children: false,
            warnings: [],
            mod_count: null,
            children: [],
          },
        ],
      },
      {
        kind: 'object',
        id: 'demo-object-interface',
        name: 'Interface',
        path: 'UI\\Interface',
        object_id: 'demo-object-interface',
        node_type: 'ui',
        is_enabled: true,
        is_effectively_active: true,
        inactive_reason: null,
        show_inactive_chip: false,
        status_kind: null,
        collapse_children: false,
        warnings: [],
        mod_count: 1,
        children: [
          {
            kind: 'mod',
            id: 'demo-mod-minimal-hud',
            name: 'Minimal HUD',
            path: 'UI\\Interface\\Minimal HUD',
            object_id: 'demo-object-interface',
            node_type: 'mod',
            is_enabled: true,
            is_effectively_active: true,
            inactive_reason: null,
            show_inactive_chip: false,
            status_kind: null,
            collapse_children: false,
            warnings: [],
            mod_count: null,
            children: [],
          },
        ],
      },
    ],
    projected_state: demoProjectedState,
  };
}
