import type { DupScanReport } from '@/shared/api/tauri/bindings.gen';
export const demoDupScanReport: DupScanReport = {
  scanId: 'demo-duplicate-scan',
  gameId: 'demo-zenless',
  rootPath: 'C:\\Demo\\Zenless\\Mods',
  totalGroups: 4,
  totalMembers: 9,
  groups: [
    {
      groupId: 'demo-duplicate-group',
      confidenceScore: 94,
      matchReason: 'Matching file hashes',
      isUnsafe: false,
      signals: [{ key: 'hash', detail: '18 matching files', score: 94 }],
      members: [
        {
          modId: 'demo-mod-1',
          version: 1,
          folderPath: 'Characters\\Nekomata\\Streetwear',
          displayName: 'Nekomata Streetwear',
          totalSizeBytes: 367_001_600,
          fileCount: 18,
          isSafe: true,
          confidenceScore: 94,
          signals: [{ key: 'hash', detail: '18 matching files', score: 94 }],
        },
        {
          modId: 'demo-mod-2',
          version: 1,
          folderPath: 'Archive\\Nekomata Streetwear Copy',
          displayName: 'Nekomata Streetwear Copy',
          totalSizeBytes: 367_001_600,
          fileCount: 18,
          isSafe: true,
          confidenceScore: 94,
          signals: [{ key: 'hash', detail: '18 matching files', score: 94 }],
        },
      ],
    },
    {
      groupId: 'demo-duplicate-lumina',
      confidenceScore: 100,
      matchReason: 'Identical BLAKE3 file set',
      isUnsafe: false,
      signals: [{ key: 'blake3', detail: '24 identical files', score: 100 }],
      members: [
        {
          modId: 'demo-mod-lumina-recolor',
          version: 1,
          folderPath: 'Environment\\Lumina Square\\Recolor',
          displayName: 'Lumina Square Recolor',
          totalSizeBytes: 184_549_376,
          fileCount: 24,
          isSafe: true,
          confidenceScore: 100,
          signals: [{ key: 'blake3', detail: '24 identical files', score: 100 }],
        },
        {
          modId: null,
          version: 1,
          folderPath: 'Downloads\\Lumina Square Recolor',
          displayName: 'Lumina Square Recolor (download)',
          totalSizeBytes: 184_549_376,
          fileCount: 24,
          isSafe: true,
          confidenceScore: 100,
          signals: [{ key: 'blake3', detail: '24 identical files', score: 100 }],
        },
      ],
    },
    {
      groupId: 'demo-duplicate-hud',
      confidenceScore: 78,
      matchReason: 'Matching file names and texture dimensions',
      isUnsafe: false,
      signals: [
        { key: 'filename', detail: '8 matching files', score: 80 },
        { key: 'dimensions', detail: '6 matching textures', score: 76 },
      ],
      members: [
        {
          modId: 'demo-mod-minimal-hud',
          version: 1,
          folderPath: 'UI\\Interface\\Minimal HUD',
          displayName: 'Minimal HUD',
          totalSizeBytes: 38_797_312,
          fileCount: 8,
          isSafe: true,
          confidenceScore: 78,
          signals: [{ key: 'filename', detail: '8 matching files', score: 80 }],
        },
        {
          modId: null,
          version: 1,
          folderPath: 'UI\\Interface\\Compact HUD',
          displayName: 'Compact HUD',
          totalSizeBytes: 36_700_160,
          fileCount: 8,
          isSafe: true,
          confidenceScore: 78,
          signals: [{ key: 'dimensions', detail: '6 matching textures', score: 76 }],
        },
      ],
    },
    {
      groupId: 'demo-duplicate-private',
      confidenceScore: 62,
      matchReason: 'Similar metadata and file layout',
      isUnsafe: true,
      signals: [{ key: 'layout', detail: '12 matching paths', score: 62 }],
      members: [
        {
          modId: 'demo-mod-private-variant',
          version: 1,
          folderPath: 'Characters\\Nekomata\\Private Variant',
          displayName: 'Private Variant',
          totalSizeBytes: 96_468_992,
          fileCount: 12,
          isSafe: false,
          confidenceScore: 62,
          signals: [{ key: 'layout', detail: '12 matching paths', score: 62 }],
        },
        {
          modId: 'demo-mod-private-alternate',
          version: 1,
          folderPath: 'Characters\\Nekomata\\Private Alternate',
          displayName: 'Private Alternate',
          totalSizeBytes: 71_303_168,
          fileCount: 12,
          isSafe: false,
          confidenceScore: 62,
          signals: [{ key: 'layout', detail: '12 matching paths', score: 62 }],
        },
        {
          modId: null,
          version: 1,
          folderPath: 'Archive\\Nekomata Private Variant',
          displayName: 'Private Variant (archive)',
          totalSizeBytes: 96_468_992,
          fileCount: 12,
          isSafe: false,
          confidenceScore: 62,
          signals: [{ key: 'layout', detail: '12 matching paths', score: 62 }],
        },
      ],
    },
  ],
};
