import type {
  GameSchema,
  WorkspaceCapabilities,
  WorkspaceExplorer,
  WorkspaceExplorerNode,
  WorkspaceObjectNode,
  WorkspacePreview,
  WorkspaceSelection,
  WorkspaceViewModel,
} from '@/shared/api/tauri/bindings.gen';

const capabilities: WorkspaceCapabilities = {
  can_toggle: true,
  can_rename: true,
  can_delete: true,
  can_move: true,
  can_toggle_safe: true,
  can_sync: true,
  can_enable_only_this: true,
  can_pin: true,
  can_edit_metadata: true,
  can_reveal_in_explorer: true,
  can_move_category: true,
  can_open_in_explorer: true,
};

interface ScrollFixtureGroup {
  objectType: string;
  folderPrefix: string;
  namePrefix: string;
  count: number;
  subCategory: string | null;
}

const scrollFixtureGroups: ScrollFixtureGroup[] = [
  {
    objectType: 'Character',
    folderPrefix: 'Characters',
    namePrefix: 'Archive Candidate',
    count: 48,
    subCategory: 'New Eridu',
  },
  {
    objectType: 'Environment',
    folderPrefix: 'Environment',
    namePrefix: 'Location Preset',
    count: 16,
    subCategory: null,
  },
  {
    objectType: 'UI',
    folderPrefix: 'UI',
    namePrefix: 'Interface Preset',
    count: 12,
    subCategory: null,
  },
];

function buildScrollableObjectFixtures(): WorkspaceObjectNode[] {
  return scrollFixtureGroups.flatMap((group) =>
    Array.from({ length: group.count }, (_, index) => {
      const position = index + 1;
      const paddedPosition = String(position).padStart(2, '0');
      const isDisabled = position % 7 === 0;
      const hasUnsafeMod = group.objectType === 'Character' && position % 9 === 0;
      const name =
        position % 11 === 0
          ? `${group.namePrefix} ${paddedPosition} with an intentionally long fixture name`
          : `${group.namePrefix} ${paddedPosition}`;
      const folderPath = `${group.folderPrefix}/${name}`;

      return {
        id: `demo-scroll-${group.objectType.toLowerCase()}-${paddedPosition}`,
        name,
        display_name: name,
        folder_path: folderPath,
        matched_entry_key: `demo-${group.objectType.toLowerCase()}-${paddedPosition}`,
        matched_alias_name: null,
        matched_confidence: 0.9,
        matched_reason: 'Fixture record for list scrolling',
        matched_source: 'demo',
        object_type: group.objectType,
        randomizer_mode: null,
        sub_category: group.subCategory,
        status: isDisabled ? 0 : 1,
        metadata: JSON.stringify({ fixture: true, position }),
        tags: '["demo-scroll"]',
        hash_db: null,
        custom_skins: null,
        is_pinned: position === 1,
        is_auto_sync: false,
        thumbnail_path: null,
        created_at: '2026-09-01T00:00:00Z',
        mod_count: 5,
        enabled_count: isDisabled ? 0 : 3,
        safe_mod_count: hasUnsafeMod ? 4 : 5,
        unsafe_mod_count: hasUnsafeMod ? 1 : 0,
        unclassified_mod_count: 0,
        is_object_disabled: isDisabled,
        has_naming_conflict: false,
        active_mod_paths: isDisabled ? null : `${folderPath}/Preset`,
        is_registered: true,
        node_kind: 'object',
        display_mode: 'unknown',
        type_chip: null,
        is_effectively_active: !isDisabled,
        inactive_reason: isDisabled ? { code: 'object_folder_disabled', args: {} } : null,
        warning_state: 'none',
        primary_warning: null,
        switch_state: isDisabled ? 'disabled' : 'enabled',
        switch_reason: isDisabled ? { code: 'object_folder_disabled', args: {} } : null,
        switch_policy_key: 'object',
        capabilities,
      };
    }),
  );
}

const objectNodes: WorkspaceObjectNode[] = [
  {
    id: 'demo-object-nekomata',
    name: 'Nekomata',
    display_name: 'Nekomata',
    folder_path: 'Characters/Nekomata',
    matched_entry_key: 'nekomata',
    matched_alias_name: null,
    matched_confidence: 0.98,
    matched_reason: 'Filename and INI match',
    matched_source: 'demo',
    object_type: 'Character',
    randomizer_mode: null,
    sub_category: 'Cunning Hares',
    status: 1,
    metadata: '{"faction":"Cunning Hares"}',
    tags: '["streetwear","favorite"]',
    hash_db: null,
    custom_skins: null,
    is_pinned: true,
    is_auto_sync: false,
    thumbnail_path: null,
    created_at: '2026-09-11T08:30:00Z',
    mod_count: 6,
    enabled_count: 4,
    safe_mod_count: 4,
    unsafe_mod_count: 2,
    unclassified_mod_count: 0,
    is_object_disabled: false,
    has_naming_conflict: false,
    active_mod_paths: 'Characters/Nekomata/Streetwear',
    is_registered: true,
    node_kind: 'object',
    display_mode: 'unknown',
    type_chip: null,
    is_effectively_active: true,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'object',
    capabilities,
  },
  {
    id: 'demo-object-lumina',
    name: 'Lumina Square',
    display_name: 'Lumina Square',
    folder_path: 'Environment/Lumina Square',
    matched_entry_key: 'lumina-square',
    matched_alias_name: null,
    matched_confidence: 0.94,
    matched_reason: 'Folder match',
    matched_source: 'demo',
    object_type: 'Environment',
    randomizer_mode: null,
    sub_category: null,
    status: 0,
    metadata: '{}',
    tags: '["night"]',
    hash_db: null,
    custom_skins: null,
    is_pinned: false,
    is_auto_sync: false,
    thumbnail_path: null,
    created_at: '2026-09-10T11:00:00Z',
    mod_count: 1,
    enabled_count: 0,
    safe_mod_count: 1,
    unsafe_mod_count: 0,
    unclassified_mod_count: 0,
    is_object_disabled: false,
    has_naming_conflict: false,
    active_mod_paths: null,
    is_registered: true,
    node_kind: 'object',
    display_mode: 'unknown',
    type_chip: null,
    is_effectively_active: true,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'object',
    capabilities,
  },
  {
    id: 'demo-object-anby',
    name: 'Anby',
    display_name: 'Anby',
    folder_path: 'Characters/Anby',
    matched_entry_key: 'anby',
    matched_alias_name: null,
    matched_confidence: 0.97,
    matched_reason: 'Filename and INI match',
    matched_source: 'demo',
    object_type: 'Character',
    randomizer_mode: null,
    sub_category: 'Cunning Hares',
    status: 1,
    metadata: '{"faction":"Cunning Hares"}',
    tags: '["combat","favorite"]',
    hash_db: null,
    custom_skins: null,
    is_pinned: false,
    is_auto_sync: false,
    thumbnail_path: null,
    created_at: '2026-09-09T09:15:00Z',
    mod_count: 3,
    enabled_count: 2,
    safe_mod_count: 3,
    unsafe_mod_count: 0,
    unclassified_mod_count: 0,
    is_object_disabled: false,
    has_naming_conflict: false,
    active_mod_paths: 'Characters/Anby/Urban Tactical',
    is_registered: true,
    node_kind: 'object',
    display_mode: 'unknown',
    type_chip: null,
    is_effectively_active: true,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'object',
    capabilities,
  },
  {
    id: 'demo-object-interface',
    name: 'Interface',
    display_name: 'Interface',
    folder_path: 'UI/Interface',
    matched_entry_key: 'interface',
    matched_alias_name: null,
    matched_confidence: 0.91,
    matched_reason: 'Category mapping',
    matched_source: 'demo',
    object_type: 'UI',
    randomizer_mode: null,
    sub_category: null,
    status: 1,
    metadata: '{}',
    tags: '["accessibility"]',
    hash_db: null,
    custom_skins: null,
    is_pinned: false,
    is_auto_sync: false,
    thumbnail_path: null,
    created_at: '2026-09-08T14:20:00Z',
    mod_count: 2,
    enabled_count: 1,
    safe_mod_count: 2,
    unsafe_mod_count: 0,
    unclassified_mod_count: 0,
    is_object_disabled: false,
    has_naming_conflict: false,
    active_mod_paths: 'UI/Interface/Minimal HUD',
    is_registered: true,
    node_kind: 'object',
    display_mode: 'unknown',
    type_chip: null,
    is_effectively_active: true,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'object',
    capabilities,
  },
  ...buildScrollableObjectFixtures(),
];

const nekomataFolders: WorkspaceExplorerNode[] = [
  {
    node_type: 'ContainerFolder',
    classification_reasons: ['Recognized mod folder'],
    id: 'demo-mod-streetwear',
    owner_object_id: 'demo-object-nekomata',
    owner_object_folder_path: 'Characters/Nekomata',
    name: 'Streetwear',
    folder_name: 'Streetwear',
    path: 'Characters/Nekomata/Streetwear',
    is_enabled: true,
    is_directory: true,
    thumbnail_path: null,
    modified_at: 1_789_283_200_000,
    size_bytes: 367_001_600,
    has_info_json: true,
    is_favorite: true,
    is_misplaced: false,
    is_safe: true,
    is_safety_classified: true,
    contains_safe_mods: true,
    contains_unsafe_mods: false,
    metadata: { author: 'Demo Artist', version: '1.2' },
    category: 'Character',
    conflict_group_id: null,
    conflict_state: null,
    warnings: [],
    node_kind: 'container',
    display_mode: 'mod_pack',
    type_chip: 'mod_pack',
    display_name: 'Streetwear',
    is_effectively_active: true,
    ancestor_disabled: false,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'mod',
    capabilities,
    can_navigate: true,
  },
  {
    node_type: 'TerminalMod',
    classification_reasons: ['Recognized mod folder'],
    id: 'demo-mod-summer',
    owner_object_id: 'demo-object-nekomata',
    owner_object_folder_path: 'Characters/Nekomata',
    name: 'Summer Palette',
    folder_name: 'Summer Palette',
    path: 'Characters/Nekomata/Summer Palette',
    is_enabled: false,
    is_directory: true,
    thumbnail_path: null,
    modified_at: 1_789_196_800_000,
    size_bytes: 82_944_000,
    has_info_json: false,
    is_favorite: false,
    is_misplaced: false,
    is_safe: true,
    is_safety_classified: true,
    contains_safe_mods: true,
    contains_unsafe_mods: false,
    metadata: null,
    category: 'Character',
    conflict_group_id: null,
    conflict_state: null,
    warnings: [],
    node_kind: 'terminal_mod',
    display_mode: 'flat_mod',
    type_chip: 'flat_mod',
    display_name: 'Summer Palette',
    is_effectively_active: false,
    ancestor_disabled: false,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'disabled',
    switch_reason: null,
    switch_policy_key: 'mod',
    capabilities,
    can_navigate: false,
  },
  {
    node_type: 'TerminalMod',
    classification_reasons: ['Recognized mod folder'],
    id: 'demo-mod-midnight-runner',
    owner_object_id: 'demo-object-nekomata',
    owner_object_folder_path: 'Characters/Nekomata',
    name: 'Midnight Runner',
    folder_name: 'Midnight Runner',
    path: 'Characters/Nekomata/Midnight Runner',
    is_enabled: true,
    is_directory: true,
    thumbnail_path: null,
    modified_at: 1_789_110_400_000,
    size_bytes: 164_626_432,
    has_info_json: true,
    is_favorite: false,
    is_misplaced: false,
    is_safe: true,
    is_safety_classified: true,
    contains_safe_mods: true,
    contains_unsafe_mods: false,
    metadata: { author: 'Mod Workshop', version: '2.0' },
    category: 'Character',
    conflict_group_id: null,
    conflict_state: null,
    warnings: [],
    node_kind: 'terminal_mod',
    display_mode: 'flat_mod',
    type_chip: 'flat_mod',
    display_name: 'Midnight Runner',
    is_effectively_active: true,
    ancestor_disabled: false,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'mod',
    capabilities,
    can_navigate: false,
  },
  {
    node_type: 'TerminalMod',
    classification_reasons: ['Safety keyword match: mature'],
    id: 'demo-mod-private-variant',
    owner_object_id: 'demo-object-nekomata',
    owner_object_folder_path: 'Characters/Nekomata',
    name: 'Private Variant',
    folder_name: 'Private Variant',
    path: 'Characters/Nekomata/Private Variant',
    is_enabled: false,
    is_directory: true,
    thumbnail_path: null,
    modified_at: 1_789_024_000_000,
    size_bytes: 96_468_992,
    has_info_json: true,
    is_favorite: false,
    is_misplaced: false,
    is_safe: false,
    is_safety_classified: true,
    contains_safe_mods: false,
    contains_unsafe_mods: true,
    metadata: { author: 'Demo Artist', version: '1.0' },
    category: 'Character',
    conflict_group_id: null,
    conflict_state: null,
    warnings: [],
    node_kind: 'terminal_mod',
    display_mode: 'flat_mod',
    type_chip: 'flat_mod',
    display_name: 'Private Variant',
    is_effectively_active: false,
    ancestor_disabled: false,
    inactive_reason: { code: 'object_folder_disabled', args: {} },
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'disabled',
    switch_reason: null,
    switch_policy_key: 'mod',
    capabilities,
    can_navigate: false,
  },
  {
    node_type: 'TerminalMod',
    classification_reasons: ['Safety keyword match: mature'],
    id: 'demo-mod-private-alternate',
    owner_object_id: 'demo-object-nekomata',
    owner_object_folder_path: 'Characters/Nekomata',
    name: 'Private Alternate',
    folder_name: 'Private Alternate',
    path: 'Characters/Nekomata/Private Alternate',
    is_enabled: true,
    is_directory: true,
    thumbnail_path: null,
    modified_at: 1_788_937_600_000,
    size_bytes: 71_303_168,
    has_info_json: false,
    is_favorite: false,
    is_misplaced: false,
    is_safe: false,
    is_safety_classified: true,
    contains_safe_mods: false,
    contains_unsafe_mods: true,
    metadata: null,
    category: 'Character',
    conflict_group_id: null,
    conflict_state: null,
    warnings: [],
    node_kind: 'terminal_mod',
    display_mode: 'flat_mod',
    type_chip: 'flat_mod',
    display_name: 'Private Alternate',
    is_effectively_active: true,
    ancestor_disabled: false,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'mod',
    capabilities,
    can_navigate: false,
  },
  {
    node_type: 'ContainerFolder',
    classification_reasons: ['Recognized mod folder'],
    id: 'demo-mod-variants',
    owner_object_id: 'demo-object-nekomata',
    owner_object_folder_path: 'Characters/Nekomata',
    name: 'Variants',
    folder_name: 'Variants',
    path: 'Characters/Nekomata/Variants',
    is_enabled: true,
    is_directory: true,
    thumbnail_path: null,
    modified_at: 1_788_851_200_000,
    size_bytes: 218_103_808,
    has_info_json: true,
    is_favorite: false,
    is_misplaced: false,
    is_safe: true,
    is_safety_classified: true,
    contains_safe_mods: true,
    contains_unsafe_mods: false,
    metadata: { author: 'Mod Workshop', version: '1.0' },
    category: 'Character',
    conflict_group_id: null,
    conflict_state: null,
    warnings: [],
    node_kind: 'container',
    display_mode: 'mod_pack',
    type_chip: 'mod_pack',
    display_name: 'Variants',
    is_effectively_active: true,
    ancestor_disabled: false,
    inactive_reason: null,
    warning_state: 'none',
    primary_warning: null,
    switch_state: 'enabled',
    switch_reason: null,
    switch_policy_key: 'mod',
    capabilities,
    can_navigate: true,
  },
];

const emptyExplorer: WorkspaceExplorer = {
  self_node_type: null,
  self_node_kind: 'object',
  self_display_mode: 'unknown',
  self_type_chip: null,
  self_is_mod: false,
  self_is_enabled: true,
  self_is_effectively_active: true,
  self_owner_object_id: null,
  self_owner_object_folder_path: null,
  self_classification_reasons: [],
  children: [],
  conflicts: [],
  ancestor_disabled_by: null,
  ancestor_disabled_path: null,
  inactive_reason: null,
};

export const demoGameSchema: GameSchema = {
  categories: [
    {
      name: 'Character',
      label: 'Characters',
      icon: 'UserRound',
      color: '#4f8cff',
      filters: [{ key: 'faction', label: 'Faction', options: ['Cunning Hares', 'Belobog'] }],
    },
    {
      name: 'Environment',
      label: 'Environment',
      icon: 'Map',
      color: '#2fbf89',
      filters: [],
    },
    {
      name: 'UI',
      label: 'Interface',
      icon: 'PanelTop',
      color: '#a855f7',
      filters: [],
    },
  ],
  filters: [],
};

function getStringField(input: unknown, key: string): string | null {
  if (typeof input !== 'object' || input === null || Array.isArray(input)) {
    return null;
  }

  const value = (input as Record<string, unknown>)[key];
  return typeof value === 'string' ? value : null;
}

function buildExplorer(selectedObjectPath: string | null): WorkspaceExplorer {
  if (selectedObjectPath !== 'Characters/Nekomata') {
    return emptyExplorer;
  }

  return {
    ...emptyExplorer,
    self_node_type: 'ObjectRoot',
    self_owner_object_id: 'demo-object-nekomata',
    self_owner_object_folder_path: selectedObjectPath,
    children: nekomataFolders,
  };
}

function buildPreview(selectedModPath: string | null): WorkspacePreview {
  const selectedNode = nekomataFolders.find((folder) => folder.path === selectedModPath) ?? null;

  return {
    selected_path: selectedNode?.path ?? null,
    selected_node: selectedNode,
    is_flat_mod_root: selectedNode?.display_mode === 'flat_mod',
    display_title: selectedNode?.display_name ?? null,
    display_subtitle: selectedNode ? 'Character / Nekomata' : null,
    mod_info_summary: selectedNode
      ? {
          actual_name: selectedNode.display_name,
          author: String(selectedNode.metadata?.author ?? 'Demo Artist'),
          version: String(selectedNode.metadata?.version ?? '1.0'),
          description: selectedNode.is_safe
            ? 'Fixture content for reviewing the existing mod details view.'
            : 'Fixture content marked unsafe so the existing safety states can be reviewed.',
          is_safe: selectedNode.is_safe,
          is_favorite: selectedNode.is_favorite,
          has_info_json: selectedNode.has_info_json,
        }
      : null,
    ini_summary: selectedNode
      ? { file_count: 2, file_names: ['Nekomata.ini', 'NekomataTextures.ini'] }
      : null,
    image_summary: selectedNode ? { image_count: 0, primary_image_path: null } : null,
    warning_summary: { state: 'none', messages: [] },
  };
}

export function buildDemoWorkspaceViewModel(input: unknown): WorkspaceViewModel {
  const selectedObjectPath = getStringField(input, 'selected_object_folder_path');
  const selectedModPath = getStringField(input, 'selected_mod_path');
  const explorerSubPath = getStringField(input, 'explorer_sub_path');
  const selection: WorkspaceSelection = {
    selected_object_folder_path: selectedObjectPath,
    explorer_sub_path: explorerSubPath,
    selected_mod_path: selectedModPath,
    current_path: selectedObjectPath ? selectedObjectPath.split('/') : [],
    reconciliation_status: 'unchanged',
    reconciliation_reason: null,
    affected_paths: [],
  };

  return {
    objects: objectNodes,
    explorer: buildExplorer(selectedObjectPath),
    preview: buildPreview(selectedModPath),
    selection,
    runtime: {
      game_id: 'demo-zenless',
      source_state: { status: 'available', message: null },
      recovery_status: 'ready',
    },
  };
}
